### ISSUE TITLE
checkout progress bar - Begriffe ändern

### ISSUE THREAD

**Issue by Ron16** [firegento/firegento-magesetup2#10]
Hall, kann mir jemand sagen, wie bzw. wo ich die Beschriftung der "checkout progress bar" ändern kann? Ich möchte die Begriffe in Deutsch übersetzen, finde aber keine Datei, in der die Begriffe vokommen. (z.B. "Shipping" oder "Review & Payments").
Die bereits installierten DE-Übersetzungen greifen leider nicht!
Vielen Dank schon mal für einen Tipp.

Ron16

**Comment by therouv** [comment]
Hi @Ron16, this is not an issue of MageSetup2. 
Please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for this question. You could also check the repository [Magento2_German_LocalePack_de_DE](https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE) which contains a German translation for Magento2 and raise your issue there.
