### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by Marx15** [firegento/firegento-magesetup2#102]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 2.0.1
* Magento version: 2.2.2
* PHP version: 7.0.27

### Issue description

Hello
I wanted to install firegento / magesetup 2 on a test shop.
have tried it over putty with this code:

composer config repositories.firegento_magesetup vcs git@github.com: firegento / firegento-magesetup2.git
composer require firegento / magesetup2: dev-develop
bin / magento module: enable FireGento_MageSetup
bin / magento setup: upgrade
bin / magento magesetup: setup: run de

Unfortunately, I get this hint:

Parse error: syntax error 'unexpected' 'in /var/www/vhosts/XXX/XXX/httpdocs/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 190
[root @ XXXXX httpdocs] # composer require firegento / magesetup2: dev-develop
PHP Warning: Module 'mcrypt' already loaded in Unknown on line 0
PHP Parse error: syntax error, 'unexpected' [', expecting') 'in / var / www / vhosts / XXX / XXX / httpdocs / vendor / magento / magento-composer-installer / src / MagentoHackathon / Composer / Magento / Plugin. php on line 190

Parse error: syntax error 'unexpected' 'in /var/www/vhosts/XXX/XXX/httpdocs/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php on line 190
[root @ XXXXX httpdocs] # bin / magento module: enable FireGento_MageSetup
-bash: bin / magento: Permission denied
[root @ XXXXX httpdocs] # bin / magento setup: upgrade
-bash: bin / magento: Permission denied

does one perhaps have an idea?

Thank you for your help

### Steps to reproduce

1. ... 
2. ... 
3. ...

**Comment by mautz-et-tong** [comment]
This seems to be Infrastructure related. Check permissions of your scripts. If you have trouble with this modules after fixing these errors, you are free to reopen this issue again.
-> bin / magento: Permission denied
-> PHP Warning: Module 'mcrypt' already loaded in Unknown on line 0

**Comment by Marx15** [comment]
Thank you for your help.

How can I check the right one and what should it be?

Thank you
