### ISSUE TITLE
Manual for Composer installatino creates an issue

### ISSUE THREAD

**Issue by itsolon** [firegento/firegento-magesetup2#107]
### General

* Module version: FireGento_MageSetup
* Magento version: 2.2.2
* PHP version: 7.0.2.2

### Manual contains small error
####this line
composer config repositories.firegento_magesetup vcs git@github.com:firegento/firegento-magesetup2.git
#####
composer require firegento/magesetup2:dev-develop
bin/magento module:enable FireGento_MageSetup
bin/magento setup:upgrade
bin/magento magesetup:setup:run <countrycode>

### fire this line on bash terminal
and composer.json file will be added with a new repository
as you can see below,, the [ ] marks are replaced with { } this causes my magento that i cannot login anymore.
{"0":"\"\/var\/www\/vhosts\/XXXXX.de\/httpdocs\/composer.json\" does not contain valid JSON\nParse error on line 56:\n...itories\": {        {            \"type\"\n---------------------^\nExpected one of: 'STRING', '}'","1":"#0 \/var\/www\/vhosts\/XXXXX.de\/httpdocs\/

############ALTERED############
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "firegento_magesetup": {
            "type": "vcs",
            "url": "git@github.com:firegento/firegento-magesetup2.git"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}
############END-ALTERED############

############STANDARD############
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        } 
    ],
    "extra": {
        "magento-force": "override"
    }
}
############END-STANDARD############

**Comment by CybotTM** [comment]
except the superfluous } at the end of your paste, the JSON code code is fine.

MAybe the parser has a fault, try replacing the zero with a name:

change: 

```json
"0": {
	"type": "composer",
	"url": "https://repo.magento.com/"
}
```

to:

```json
"repo.magento.com": {
	"type": "composer",
	"url": "https://repo.magento.com/"
}
```

**Comment by frostblogNet** [comment]
This issue does not seem to be relatet to magesetup2. Please reopen it if is get this wrong and is still relevant to you.

Thanks
