### ISSUE TITLE
 Magento 2 Firegento Magestup VAT display 0% tax - MwSt.-Anzeige 0% Steuern

### ISSUE THREAD

**Issue by magepur** [firegento/firegento-magesetup2#108]
Hello,
I installed the extension step by step following the instructions, emptied cache and re-indexed everything. I have checked country options, localization and shop information. Everything is registered correctly. But unfortunately everywhere in the products "incl. 0% taxes". Maybe someone knows why that could be?

Hallo,

 

ich habe die Extension nach der Anleitung Schritt für Schritt installiert, Cache geleert und alles neu indexiert. Länderoptionen, Lokalisierung und Shopinformationen habe ich überprüft. Alles ist richtig eingetragen. Aber leider steht überall in den Produkten "inkl. 0% Steuern". Weiß jemand vielleicht, woran das liegen könnte?

 

Vielen Dank im Voraus!

**Comment by leptoquark1** [comment]
Es werden neue Steuersätze angelegt, die du den Produkten auch zuweisen musst.

![bildschirmfoto 2018-03-19 um 10 12 09](https://user-images.githubusercontent.com/13577480/37586998-4bbca2f0-2b5e-11e8-9163-745604d31a0f.png)
![bildschirmfoto 2018-03-19 um 10 13 13](https://user-images.githubusercontent.com/13577480/37586999-4bd8306a-2b5e-11e8-8270-7e2e6165597c.png)

**Comment by Waldemar-Denke** [comment]
Hab das gleiche Problem. Die Produkte sind zugeordnet. Die Einstellungen sind in Ordnung. Reindex, Cache geleert. Trotzdem "Inkl. 0% Steuern"

**Comment by magepur** [comment]
Ich habe alle Einstellungen mehrmals kontrolliert. Alle Einstellungen sind richtig. Trotzdem werden die MwSt. nicht angezeigt. Entweder übersehen wir eine notwendige Einstellung oder ist irgendwo ein Bug.

**Comment by mautz-et-tong** [comment]
Dieses Problem tritt meistens auf, wenn das Setup mehrmals durchgeführt wurde. Die Steuer IDs in der Datenbank beginnen dann nicht mehr mit 0,1,2 usw. sondern mit 7,8 usw. Die den Produkten zugeordneten Steuern sind jedoch 0,1 usw. Daher dann 0 %. Bitte mal in den Tax-Tabellen nach den IDs schauen und ggf. ALLE Steuern löschen und EINMAL das Setup ausführen.

**Comment by magepur** [comment]
Vielen Dank für die Antwort. Aber daran liegt es nicht. Ich habe gerade die Tabelle kontrolliert.
Die IDs sind richtig. Die Firegento Erweiterung habe ich auch nur einmal installiert.
Die IDs fangen ab 1 an und das ist auch richtig.

 1- Vollbesteuerte Artikel 
 2- Ermäßigtbesteuerte Artikel 
 3- Vollbesteuerter Versand
 4- Ermäßigtbesteuerter Versand
 5- Endkunden
 6- USt.-pflichtige Unternehmen
 7- USt.-befreite Unternehmen

**Comment by Waldemar-Denke** [comment]
Ich habs. @magepur gehe zu "Kunden->Kundengruppen". Öffne jeden und speicher den einfach ab.
Ich habe meine Daten über das Migration Tool von 1.7. Dort war bei den Kundengruppen in der Datenbank `tax_class_id = 3`.  Die neue TaxClassId für Endkunden ist 5 (Endkunden). 

Fix for 0% Tax Calculation with FireGento could be to change tax_class_id in Cutomer Group Configuration. Navigate to **Customer->Customer Groups** open each and save it. It changes the tax_class_id in customer_group table to > 5.

**Comment by magepur** [comment]
@Waldemar-Denke 
Waldemar, du bist ein Held ;). Endlich hat es geklappt. Auf diese Idee wäre ich nie gekommen. Nachdem ich alle Kundengruppen aktualisiert habe, werden jetzt die Steuersätze richtig angezeigt.

Super vielen Dank.

**Comment by DrMabuse-2017** [comment]
Wow...dieser Tip ist der Beste.
Habe 4 Stunden gesucht und alles nochmals und nochmals geprüft. Ohne Erfolg.
Dieser Tip hat geholfen. Und in 2 Minuten war das Problem beseitigt.
Magento 2.2.4

**Comment by jakob-sc** [comment]
Das es so einfach wird hätte ich auch nicht geglaubt, aber wenn ich ein Produkt in das Suchfeld eingebe, werden mir bei den Produktvorschlägen immernoch die 0% angezeigt. Hat jemand eine Idee wie man das lösen kann, bzw habe nur ich diesen Fehler?

**Comment by Waldemar-Denke** [comment]
Probier mal den Index für Suche und Produkte neu aufzubauen.

**Comment by jakob-sc** [comment]
Verändert sich leider nichts!

**Comment by frostblogNet** [comment]
Ich kann den Fehler aktuell nicht nachstellen auch auf der Suchseite werden mir die richtigen Steuern ausgewiesen.

Ich mach das Ticket erstmal zu sollte es noch relevant sein bitte erneut öffnen.
