### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by nepomuk-hirsch** [firegento/firegento-magesetup2#11]
Hi all,

I managed to install Firegento-Magesetup2 via composer and "bin/magento magesetup:setup:run de" completed without any issues. In the backend, under Shops -> Configuration -> Advanced -> Advanced, I can see that "FireGento_MageSetup" is activated. Moreover, under Shops -> Configuration -> General, I can see a section called "Imprint". So I assume everything is installed correctly.

However, I can't find any further configuration settings like, e.g. no "click here to configure" banner after the installation and no imprint is visible on the public frontend.  

I'm wondering how to configure everything and make e.g. the imprint visible. Any hints?

BTW: I'm using a Bitnami stack on AWS EC2.

**Comment by therouv** [comment]
Hi @nepomuk-hirsch only the setup via CLI is currently implement. You can run the configuration for German stores like this:
`php -f bin/magento magesetup:setup:run de`
