### ISSUE TITLE
Tax for Belgium

### ISSUE THREAD

**Issue by Kirycool** [firegento/firegento-magesetup2#110]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: x.x.x
* Magento version: 1.9.2
* PHP version: 5

### Issue description

No tax for Belgium => could you add this please ? Thanks !

**Comment by mautz-et-tong** [comment]
Please feel free to update the `setup`node for BE in etc/magesetup.xml according to other already set up nodes like de

**Comment by frostblogNet** [comment]
This ticket has been created in the wrong repository. It extension is for magento 2 not for 1.
So I will close this here. If it is till relevant please create on in https://github.com/firegento/firegento-magesetup

Thanks
