### ISSUE TITLE
How to suppress tax details in product list

### ISSUE THREAD

**Issue by OvalMedia** [firegento/firegento-magesetup2#111]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 2.0.1
* Magento version: 2.2.3
* PHP version: 7.1.15

### Issue description
How can I suppress the display of tax details in product lists? I know I can hide them with css but I want them gone completely.

Thank you

**Comment by masi** [comment]
Add this snippet to the di.xml file of your theme/main module:
```
    <type name="Magento\Framework\Pricing\Render">
        <plugin name="mageSetupAddPriceHints" type="FireGento\MageSetup\Plugin\Pricing\AroundRenderPlugin" disabled="true"/>
    </type>
```

**Comment by DocOlson** [comment]
This removes the tax details everywhere. I want them gone in product lists only, not on the product detail page.

**Comment by masi** [comment]
That's true.
Then try this in catalog_category_view.xml:
```
<referenceBlock name="magesetup.product.price.details" remove="true" />
```

**Comment by juliankoehn** [comment]
Bit late, but others will come:

Magento_Catalog\layout\catalog_category_view.xml
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
      <referenceBlock name="magesetup.product.price.details" remove="true" />
    </body>
</page>
```

**Comment by frostblogNet** [comment]
Thanks @juliankoehn your solution seem to be valid. 

I will close this issue here. Feel free to reopen it.

**Comment by OvalMedia** [comment]
Long time ago but I have to pick up on this. Removing the block `magesetup.product.price.details` removes the price block for an entire page/handle.

I would like to very selectively remove it from product lists. Example: currently I am working on a product view page and the main product should have those price details. But the up-/crosssell product list below should not display that block. To this day I was using regex to remove them from the rendered html but that feels very quirky and unreliable. 

Is there a way? If not, could you add it?

Thx.
