### ISSUE TITLE
how to configure afterwards, after installation, to display the shipping link in product?

### ISSUE THREAD

**Issue by hub2000** [firegento/firegento-magesetup2#114]
Question,

how to configure afterwards, months later after installation, to display the shipping link in product?

I know there is a details.phtml, but a cannot find the configuration file where is stored the "$shippingCostUrl" setting which is needed for this
Is it in the database?

Edit:
seems to search for:
$this->scopeConfig->getValue('catalog/price/cms_page_shipping');

shall i generate a cms page in order to display the link?

What is the name? "shipping" did not work

**Comment by sprankhub** [comment]
You just need to configure the "CMS Page for Shipping Info" under Stores > Configuration > Catalog > Catalog > Price.
