### ISSUE TITLE
use tags for versioning and packist.org for distribution

### ISSUE THREAD

**Issue by CybotTM** [firegento/firegento-magesetup2#115]
### Issue description

Can you please start using tags, so we can pin to specific version when adding the module to composer.json?

And include your package on packagist.org, so we can just run:

`composer require firegento/magesetup2:1.0.0
`

without `composer config repositories ...`

**Comment by Emanuel-23** [comment]
+1

**Comment by sprankhub** [comment]
This has already been done: https://packagist.org/packages/firegento/magesetup2
