### ISSUE TITLE
install problems via console

### ISSUE THREAD

**Issue by lgt** [firegento/firegento-magesetup2#12]
So I try to install but drops me the following 

`bin/magento magesetup:setup:run de`

`  [ErrorException]            
  Undefined index: arguments 
   magesetup:setup:run country [processors1] ... [processorsN]`

**Comment by davidverholen** [comment]
I think I also had this Problem in production Mode with precompiled DI files. However, running it in developer mode worked. But, I have no idea why since I did not have the time to dig deeper into it.

**Comment by lgt** [comment]
thanks a lot seems to work like that!
