### ISSUE TITLE
Not compatible with Magento 2.3

### ISSUE THREAD

**Issue by in-session** [firegento/firegento-magesetup2#127]
After installation, there will be problems with all products inside the catalog. All articles are displayed in the frontend, also the sub-articles of the configurable products which are not in the catalog. After import, the visibility setting of all products is no longer considered.

### General

* Module version: latest dev
* Magento version: 2.3.0
* PHP version: 7.2.10
* Install via composer (de)

**Comment by sprankhub** [comment]
Are you 100% sure that this is related to MageSetup? Did you remove MageSetup and check if the issue is solved?

**Comment by in-session** [comment]
I assume :-)

In the backend all items of the list are labeled visibility 'catalog,search'.
If we open the sub item of a configurable product the visibilty is "Not Visible Individually".
Even Magento itself is very slow, after import.
I will test it again today on a new installation without other modules, I'll write you again.

- Installing firegento/magesetup2 (dev-develop 4688e44): Loading from cache
Writing lock file
Generating autoload files
.../magento2 > bin/magento module:enable FireGento_MageSetup

Composer steps:
composer config repositories.firegento_magesetup vcs git@github.com:firegento/firegento-magesetup2.git
composer require firegento/magesetup2:dev-develop
bin/magento module:enable FireGento_MageSetup
bin/magento setup:upgrade
bin/magento magesetup:setup:run de

php_cli bin/magento setup:upgrade
php_cli bin/magento setup:di:compile
php_cli bin/magento setup:static-content:deploy

**Comment by arumcomputer** [comment]
Same kind of problem here. Updated a store from 2.2.4 to 2.3.0 and no tax information is printed anymore in the frontend. But that is not enough, all configured products are shown without the possibility to enter options in frontend. So all Options (dropdowns, inputs, file uploads) are missing.
did a rollback to 2.2.4 and everything works as expected.

**Comment by stkrelax** [comment]
Same here. 
**versions**
"magento/product-community-edition"  "version": "2.3.1"
"firegento/magesetup2" "version": "v0.1.1"

**steps to reproduce**

- Install fresh 2.3.1 magento CE
- deploy sample data
- run bin/magento magesetup:setup:run de

actual Result
![grafik](https://user-images.githubusercontent.com/48922246/57228629-86848780-7014-11e9-8cb8-6760edd879a6.png)

**Comment by hubertus2017** [comment]
Hello,
we want to upgrade to M2.3.1.

Is there a way forward? Did you fixed it somehow?

Hubertus

**Comment by helmuthva** [comment]
Is this project dead?

**Comment by frostblogNet** [comment]
@dh1984 provided a path for this issue. Please try it with the new version @hubertus2017

**Comment by hubertus2017** [comment]
Hello,
thank you very much :-)

However, i still did not get the following point:
If i have a working installation, want to upgrade to magento 2.3.x, do i have to
- upgrade firegento/magesetup2
- upgrade magento to 2.3.x
- run the command "run bin/magento magesetup:setup:run de"   YES or NO? is it required to be run also in upgraded installations?

Hubertus

**Comment by dh1984** [comment]
i think you can only upgrade to magento 2.3.x, because the products have the right tax classes and correct cms pages are installed. And the command: magesetup:setup:run de is only needed by a fresh installation
