### ISSUE TITLE
Hilfe bei Steueranzeige & -berechnung

### ISSUE THREAD

**Issue by 2EyeTec** [firegento/firegento-magesetup2#139]
Ich benötige folgende Funktion und Hilfe bei der Umsetzung in meinem deutschen Shop:
1. bei Unternehmen aus Deutschland (mit USt-ID) soll die Preisanzeige ohne USt erfolgen, der dazugehörige Text soll lauten zzgl. 19% USt und es soll (beim Checkout?) auch 19% USt berechnet werden
2. bei EU Unternehmen (mit USt-ID) und nicht-EU Kunden: Preisanzeige ohne USt, Text zzgl. 0%, Berechnung 0%

Die Berechnung funktioniert prinzipiell, leider wird bei DE Unternehmen die USt inkl. angezeigt (Preis und Text) und bei "Welt" Kunden wird als Text inkl. 19% angezeigt, obwohl keine USt angezeigt/berechnet wird.

Hier die konkreten Fragen:
* Wo ändere ich die entsprechenden Texte, wie kann ich Texte hinzufügen (z.B. zzgl. 19% USt)
* Wie erreiche ich dass bei DE Unternehmen die Anzeige ohne USt die Berechnung aber zzgl. Ust erfolgt?

Danke!

Magento Community 2.3.1

**Comment by frostblogNet** [comment]
Hallo @2EyeTec 

wir als Firgento Verein können dir bei deinem Problem leider nicht helfen. Daher wäre es gut wenn du dir einen Freelancer oder ein Agentur suchst die dieses Feature für dich umsetzen.
