### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by MYITWORKS** [firegento/firegento-magesetup2#14]
Hi there,

Is it possible to give a step by step installation instruction?
I really tried everything (composer.json, etc.) but installation wont word.

Every time i edit comoser.json and i try to call http://<magento-serverip>/setup/#/select-version
the system doesn't react any more.

Edit says:
- ubuntu 16.04
- apache 2.4
- php 7.0
- magento 2.0.5 clean install with sample data (nothing else)

**Comment by scriptserv** [comment]
Hi,
1.  Edit the composer.json in MagentoRoot... (Copy and paste)
Should look like this:

"repositories": [
       {
           "type": "composer",
           "url": "https://repo.magento.com/"
       },
       {
           "type": "vcs",
           "url": "https://github.com/firegento/firegento-magesetup2"
       }
   ],

2. Terminal/Konsole in MagentoRootFolder - 
   "composer require firegento/magesetup2 @dev"
   "php bin/magento module:enable FireGento_MageSetup"  
   "php bin/magento setup:upgrade"
   "php bin/magento magesetup:setup:run de" -> de is the language Code
   "php bin/magento setup:static-content:deploy"
   "php bin/magento cache:flush"

PS. Eventually try the installation before installing/get the Sample Data... - this was my Problem

Hope this helps,
Dennis

**Comment by MYITWORKS** [comment]
Hey Dennis,

Your instruction worked like a charm.

Just a little addition: after

"php bin/magento cache:flush"

when in called the website (front- or backend) i got an error 500.

I had to reset the file permission with

"chown -R www-data:www-data /var/www/html/"

(i did all commands as root-user in cli)

Big thanks for the quick reply and greetings from Nuernberg,
Alex

Issue can be closed.

**Comment by scriptserv** [comment]
Hey Alex,
thanks for the tip.

I created a pull request with a "Installation Step by Step".

https://github.com/firegento/firegento-magesetup2/pull/15

Have a nice weekend and greetings from Frankfurt,
Dennis
