### ISSUE TITLE
Tax rate not updated on product page with configurable product

### ISSUE THREAD

**Issue by domi-nique** [firegento/firegento-magesetup2#140]
### General
* Module version: latest dev
* Magento version: 2.3.2
* PHP version: 7.2.12

### Issue description
I have a configurable product with two simple products inside. One has a tax rate of 19%, one has a tax rate of 7%. In frontend, when choosing the 7% product, there is still the tax rate of the parent product shown on product page. The taxrate is not updated on product page.
...

### Steps to reproduce

1. Add a configurable product with two configured products with different tax rates
2. Have a look on the product page and choose different versions via dropdown.
3. The tax details are not updated on product page.

**Comment by sprankhub** [comment]
Closing due to lack of feedback. Feel free to re-open, @domi-nique.
