### ISSUE TITLE
simple product sku not showing at shopping card only configurable product sku

### ISSUE THREAD

**Issue by senders** [firegento/firegento-magesetup2#142]
I have set "Visible on Checkout" to yes for the sku attribute.

The problem here is, when you have a configurable product and you put your decision int o the shopping card, only the configurable sku is shown on the shopping card page and not the simple product sku which should be.

Any ideas?

**Comment by sprankhub** [comment]
I think this is expected behaviour. This is how Magento works (using the configurable data and only using / showing the simple product as an option) and has nothing to do with MageSetup.
