### ISSUE TITLE
.price-details always show Incl. Shipping Costs

### ISSUE THREAD

**Issue by arumcomputer** [firegento/firegento-magesetup2#143]
The .price-details div on the product details page always show Incl. shipping costs
---
Auf der Produktdetailseite steht immer "inkl. Versandkosten"...

### General

* Module version: dev-develop
* Magento version: 2.3.3
* PHP version: 7.2

### Issue description
The .price-details div on the product details page always show Incl. shipping costs no matter what is configured. The prices are without shipping costs.
---
Auf der Produktdetailseite steht immer "inkl. Versandkosten". Dabei sind die Preise ohne Versandkosten angegeben. Mit einer Konfiguration kann dieses Verhalten offenbar nicht geändert werden.

### Steps to reproduce

1. Create a configurable product (not testet with other types) 
2. set a weight 
3. use table rates for calculation shipping costs
4. visit the products detail page

**Comment by itsolon** [comment]
I often have the same problem but i remember then that i have perhaps accidentally renamed shipping cms page. and then its not assigned anymore
have a look 
![liefer-und-versand](https://user-images.githubusercontent.com/10437947/68457190-f6f8a500-01ff-11ea-8740-c3cc6cd80780.PNG)

**Comment by arumcomputer** [comment]
yeah, it seems I was missing that setting. it now works as expected. Thanks
