### ISSUE TITLE
Can I just retrigger tax rules creation after migration from M1?

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-magesetup2#146]
Hi,
I migrated my data from M1 to M2 and now the tax rules are like the ones from M1.
How can I retrigger just the creation of the tax rules the module provides for M2?
All other steps of `bin/magento magesetup:setup:run` like CMS, etc. are fine and should not be changed.
Thanks for the help.

### General

* Module version: 0.1.2
* Magento version: 2.3.3
* PHP version: 7.2

**Comment by frostblogNet** [comment]
Hi @grossmann,

I think the easiest way is to create a setup script which just triggers the FireGento\MageSetup\Model\Setup\SubProcessor\TaxSubProcessor . Call the process function and hand over the config option.
