### ISSUE TITLE
Error if using email_footer.phtml in email template

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-magesetup2#147]
### General

* Module version: 0.1.2
* Magento version: 2.3.3
* PHP version: 7.2.x

### Issue description
If I try to add imprint and other info into my email footer template using the "email_footer.phtml" template the following error is thrown:
``` Error filtering template: Invalid method FireGento\MageSetup\Block\Imprint\Content::__ ```

I reference it in the email template like this:
```{{block class="FireGento\MageSetup\Block\Imprint\Content" template="FireGento_MageSetup::imprint/email_footer.phtml"}}```

Other templates like "address.phtml" work fine.

**Comment by sprankhub** [comment]
Thanks for the report @grossmann. Should be fixed with the referenced pull request.
