### ISSUE TITLE
Error when including imprint templates in email templates

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-magesetup2#149]
### General

* Module version: 0.1.2
* Magento version: 2.3.3
* PHP version: 7.2.x

### Issue description
I included some imprint templates (e.g. view/frontend/templates/imprint/address.phtml) in my email `footer.html` template like this:
`{{block class="FireGento\MageSetup\Block\Imprint\Content" template="FireGento_MageSetup::imprint/address.phtml"}}`
In the email template preview the info shows up correctly as well as if I sent a contact form email.
But using it in a sales email template like `order_new.html` I get the following error in the sent email.
`Error filtering template: Invalid template file: 'FireGento_MageSetup::imprint/bank.phtml' in module: 'FireGento_MageSetup' block's name: 'imprint\content_1'`
Do I something wrong in calling the template?

Thanks for the help!

**Comment by sprankhub** [comment]
Sorry for the late reply! I can reproduce this issue. Could you verify that this is fixed if you move `view/frontend/templates/imprint` to `view/base/templates/imprint`?
