### ISSUE TITLE
Remove display of tax details on grouped products

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-magesetup2#150]
Related issue: #56 

### General

* Module version: 1.2.1
* Magento version: 2.3.3
* PHP version: 7.2.x
### Issue description
Magento 2.3.3 doesn't show a price on grouped products (only in the list for each of the associated simple products).
Therefore the tax and shipping cost details shouldn't be shown there as well, but they are.

### Steps to reproduce

1. Create a grouped product with at least one simple product associated
2. See the tax and shipping info right below the delivery time info as no price is shown.

**Comment by sprankhub** [comment]
If prices are still shown (no matter where), doesn't it then still make sense to have a tax hint? Maybe it is just at a weird place for grouped products?

**Comment by grossmann** [comment]
The tax hint is (sensfull) shown on the single items but also on the grouped product which has no price by itself. See the image for better understanding.
![grafik](https://user-images.githubusercontent.com/1866724/72503546-4250b480-383c-11ea-8999-0d0da41fba90.png)

**Comment by sprankhub** [comment]
Fixed in #155.
