### ISSUE TITLE
Support for php7.3 missing

### ISSUE THREAD

**Issue by SimJoSt** [firegento/firegento-magesetup2#151]
### General

* Module version: 0.1.2
* Magento version: 2.3.4
* PHP version: 7.3

### Issue description
No support for php7.3

### Steps to reproduce
Use latest version.

**Comment by SimJoSt** [comment]
Support had been added with this commit https://github.com/firegento/firegento-magesetup2/commit/1e99c882e2cedecfc4e894d777d2fd2095945272 from @jwundrak in October 2019, but since no version has been tagged.

@frostblogNet could you please a new version with this feature?

**Comment by frostblogNet** [comment]
@SimJoSt have you tried to use the develop branch with 7.3?

**Comment by jwundrak** [comment]
@frostblogNet :
Sure, that is an option, but it would be (also for us) great, if firegento can tag this, cause it is much better, than add an repo to `composer.json` and use git-commits as references. (e.g. `minimum-stability`)

**Comment by frostblogNet** [comment]
@SimJoSt Of cause we will tag a version. My question was if you had already tried the extension with php 7.3.

**Comment by frostblogNet** [comment]
@SimJoSt tagged version v.0.2.0 with php7.3 support.

**Comment by SimJoSt** [comment]
@frostblogNet thanks. Unfortunately in the tag description there is a typo: https://github.com/firegento/firegento-magesetup2/releases/tag/v0.2.0  
It says `php7.4` instead of `php7.3` :)

**Comment by sprankhub** [comment]
Fixed @SimJoSt :)
