### ISSUE TITLE
Registry key "isSecureArea" already exists

### ISSUE THREAD

**Issue by SimonGSGmbH** [firegento/firegento-magesetup2#158]
In Registry.php line 60:
  Registry key "isSecureArea" already exists
magesetup:setup:run <country> [<processors>...]

Kommt direkt nach dem Versuch des Setups...

Magento 2.3.5-p1

**Comment by frostblogNet** [comment]
Hello @SimonGSGmbH 

Thanks for you information here. Sadly I was unable to reproduce your issue. 

I will close this issue for now. If you have more information feel free to reopen it agian.

**Comment by tdachev** [comment]
The Problem still exists on Magento ver. 2.3.5-p2

**Comment by sprankhub** [comment]
@tdachev then... Could you add clear steps to reproduce? Happy to reopen then. However, we were unable to reproduce last time we tried.

**Comment by sprippen** [comment]
The Problem still exists on Magento ver. 2.3.5

This error happens to the command

php bin/magento magesetup:setup:run it

In Registry.php line 60:
                                              
  Registry key "isSecureArea" already exists
                                              
magesetup: setup: run <country> [<processors> ...]

**Comment by sprippen** [comment]
Same website but with outdated magento, so to version 2.3.3, the problem is not present

**Comment by sprankhub** [comment]
Hmm we could not reproduce this locally, but probably, because we did not use HTTPS. @SimonGSGmbH @tdachev @sprippen, could you confirm that you had this issue on an HTTPS-page?

**Comment by SimonGSGmbH** [comment]
Server is PHP 7.3.23 on nginx including HTTPS
