### ISSUE TITLE
graphic issue with widgets and buttons

### ISSUE THREAD

**Issue by MYITWORKS** [firegento/firegento-magesetup2#16]
Hi there,

Once again a problem. This time a graphical issue:

As already pointed out in [#21](https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/21) at splendidinternet/Magento2_German_LocalePack_de_DE

there is a graphical issue with the button overlay

![german locale uberlagerung](https://cloud.githubusercontent.com/assets/18720799/14910714/3f49853e-0df0-11e6-9762-6c6ebe762eae.JPG)

temp public URL for you:
http://87.138.199.231:8282/ (just a dev-enviroment, could be offline sometimes)

ubuntu 16.04
apache 2.4
php 7

magento 2.0.5
sample data
firegento-magesetup2
Magento2_German_LocalePack_de_DE

Cheers,
Alex

**Comment by MYITWORKS** [comment]
Hello Folks,

I hope you had a great weekend.

Anyone here who can approve this problem?

Cheers,
Alex

**Comment by scriptserv** [comment]
Hi Alex,
i had the same Problem but no solution - i just deinstalled the sample data and now everything works fine.
Greets, 
Dennis

**Comment by MYITWORKS** [comment]
Hi Dennis,

Deinstalling the sample data doesn't work. On the Blocks "what's new" and "hot sellers" on the start page even newly generated articles have the same graphical issu

Greets,
Alex

**Comment by frostblogNet** [comment]
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks
