### ISSUE TITLE
Prepare magesetup2 to work with php7.4 and magento 2.4.x

### ISSUE THREAD

**Issue by frostblogNet** [firegento/firegento-magesetup2#174]
### General

* Module version: >0.2.0
* Magento version: 2.4.x
* PHP version: 7.4

### Issue description

We have to make sure that magesetup will work with magento 2.4.x and php7.4

**Comment by Emanuel-23** [comment]
Its time, but unfortunately there is no update. No support for PHP 7.4.

+1

**Comment by sprankhub** [comment]
@Emanuel-23, could you please test the module on Magento 2.4 with PHP 7.4 and report back? Thanks!

**Comment by jg-development** [comment]
Hi,
a scan with phpcompatibility shows no problems with 7.4.
And it works for me in a standard shop 2.4 (+ some extensions)

**Comment by DRogmann** [comment]
Hi,
i installed a new and clean Magento 2.4 via composer.
PHP Version 7.4.8
Command i used: composer require firegento/magesetup2
Result: [InvalidArgumentException]
  Package firegento/magesetup2 at version  has a PHP requirement incompatible with your PHP version (7.4.8)

**Comment by codedge** [comment]
@DRogmann Yes, this package is not compatible with PHP 7.4 yet.

@sprankhub Any plans to release a version compatible with PHP 7.4 / M2.4?

**Comment by jg-development** [comment]
Could this be merged and closed plz?

**Comment by sprankhub** [comment]
@jg-development it is not as easy as this. We still need to fix the Travis build for 2.4. If you want to help, we are more than happy!

By the way, you can still use this module with 2.4, just not with PHP 7.4 yet.

**Comment by jg-development** [comment]
Ok I wasnt aware of the travis build.
Just fyi: It is possible to install with the composer option "--ignore-platform-reqs" and php 7.4

**Comment by frostblogNet** [comment]
@sprankhub I tink magento 2.4 is php7.4 only. I would recomment to make a support branch for 2.4 and to make a beta release. We would have to rewrite every test because of phpunit 9 and Magento will also update the 2.3 version with PHP 7.4 support in May 2021.

**Comment by sprankhub** [comment]
@frostblogNet composer-wise, it supports 7.3 and 7.4. Documentation-wise, it is semi-supported. From the [DevDocs](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html#php):

> Magento supports PHP 7.4.0. You can install Magento 2.4.0 with 7.3, but it is not tested or recommended.

Feel free to create such a workaround. I will try to work on full 2.4 support soonish, but time...

**Comment by sprankhub** [comment]
As feared, there was a bit more work needed to get this done (see #183).

**Comment by sprankhub** [comment]
Fixed in [version 0.4.0](https://github.com/firegento/firegento-magesetup2/releases/tag/v0.4.0).
