### ISSUE TITLE
Disable "delivery time" on Product View Page.

### ISSUE THREAD

**Issue by lohmann-k** [firegento/firegento-magesetup2#181]
### General

* Module version: 0.3.0
* Magento version: 2.3.5 and 2.4.0
* PHP version: 7.3

### Issue description

How can i disable "delivery time" ("Lieferzeit") on Produkt View Page?

**Comment by sprankhub** [comment]
There is no setting for that. You can use the following XML in the `catalog_product_view.xml` of your theme to remove the block:

    <referenceBlock name="product.info.delivery" remove="true"/>
