### ISSUE TITLE
Shop down after manual installation.

### ISSUE THREAD

**Issue by John-Lock-GT** [firegento/firegento-magesetup2#189]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: x.x.x
* Magento version: 2.3.x
* PHP version: x.x.x

### Issue description

After manually installing Firegento (with root user) my (Test-)Shop is down. Please help. Thanks.
PS: I meticulously followed the installation guide.

**Comment by sprankhub** [comment]
Could you be a bit more specific than "down"? However, just installing the module should not break your shop at all.
