### ISSUE TITLE
Werden die Dateien ins Root-Verzeichnis kopiert?

### ISSUE THREAD

**Issue by derKrauter** [firegento/firegento-magesetup2#19]
Hallo, 
werden die Dateien ins Root-Verzeichnis kopiert?
Grüße DerKrauter

**Comment by therouv** [comment]
Hallo @derKrauter 
idealerweise (und empfohlenerweise) installierst Du die Extension mit composer. 

Anderenfalls musst du unter "app/code" einen Ordner "FireGento" und darin einen Ordner "MageSetup" installieren. Anschließend die Dateien aus diesem Repository dort reinkopieren und anschließend `php bin/magento setup:upgrade` ausführen, damit die Extension korrekt initalisiert wird.
