### ISSUE TITLE
issue with overriding delivery.phtml from vendor directory in custom theme

### ISSUE THREAD

**Issue by vertic4l** [firegento/firegento-magesetup2#193]
### General

* Magento version: 2.4
* PHP version: 7.3

### Issue description

Need to override delivery.phtml from vendor directory but don't get it working.

**Comment by sprankhub** [comment]
What have you tried so far?

Should be doable if you add a file `path/to/your/theme/FireGento_MageSetup/templates/product/list/delivery.phtml`.

**Comment by vertic4l** [comment]
@sprankhub Ah i see, ya that makes sense now. Thanks for your help!
