### ISSUE TITLE
composer update firegento/magesetup2 failed

### ISSUE THREAD

**Issue by jburkhardt** [firegento/firegento-magesetup2#194]
### General

* Module version: dev-develop
* Magento version: 2.3.4
* PHP version: 7.2

### Issue description

I have installed the `dev-develop` version of the module a while ago and the module runs fine with Magento 2.3.4. However, it is not possible to run composer updates, change the module version or even remove the package with composer.

`composer update firegento/magesetup2` fails

`composer require firegento/magesetup2 "0.4.1"` fails

`composer remove firegento/magesetup2` fails

### Error

`Update failed (Failed to execute git show-ref --head -d fatal: Not a git repository) `

### Information

* git is installed
* update of other modules is possible without any issues

### Screenshot

<img width="904" alt="Bildschirmfoto 2021-01-26 um 18 49 42" src="https://user-images.githubusercontent.com/5146122/105887020-73e18b80-600b-11eb-83ed-1629ab619ac6.png">

### Troubleshooting

Any advice how to trouble shoot this?

**Comment by sprankhub** [comment]
That sounds very strange. Could you try to delete the `vendor` directory and try again?

**Comment by jburkhardt** [comment]
Yes that worked. Thank you! I deleted `vendor/firegento/magesetup2` and installed the module from scratch.
