### ISSUE TITLE
Fix PHP Code Sniffer Issues

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-magesetup2#196]
See https://github.com/firegento/firegento-magesetup2/actions/runs/655516803

### General

* Module version: x.x.x
* Magento version: x.x.x
* PHP version: x.x.x

### Issue description

...

### Steps to reproduce

1. ... 
2. ... 
3. ...

**Comment by in-session** [comment]
@sprankhub 

Hi after update into the new merge we get the follow error:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Ungültige Methode FireGento\MageSetup\Block\Product\Delivery\Interceptor:: helper

Exception #0 (Magento\Framework\Exception\LocalizedException): Ungültige Methode FireGento\MageSetup\Block\Product\Delivery\Interceptor:: helper
<pre>#1 FireGento\MageSetup\Block\Product\Delivery\Interceptor->__call() called at [vendor/firegento/magesetup2/view/frontend/templates/product/list/delivery.phtml:16]

```
magesetup2/view/frontend/templates/product/list/delivery.phtml:16:
```
//$_helper = $block->helper('Magento\Catalog\Helper\Output');
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
```

**Comment by sprankhub** [comment]
Wow, you are fast :) Thanks for testing! Which exact Magento version are you using?

**Comment by in-session** [comment]
2.4.2 :-)

**Comment by sprankhub** [comment]
@in-session could you please test if https://github.com/firegento/firegento-magesetup2/pull/198 works for you? I now switched to a default Magento template. I do not see any reason why we should use our own old and unmaintained template.

**Comment by in-session** [comment]
@sprankhub
Works fine, thanks for fixing
