### ISSUE TITLE
Install via Composer

### ISSUE THREAD

**Issue by simadesign** [firegento/firegento-magesetup2#2]
Can you give me a hint, how to install the modul via composer?
Do I have to add a rep?

I tried that: composer config -g repositories.firegento composer http://packages.firegento.com
and composer require firegento/magesetup2   but it didn't work.

Regards

**Comment by therouv** [comment]
Hi @simadesign the module is currently not available on packages.firegento.com
You can always add the repository directly to your `composer.json` like this:

```json
{
  "type": "git",
  "url": "https://github.com/firegento/firegento-magesetup2.git"
}
```

**Comment by simadesign** [comment]
Sry I am new with the composer. Where must I add it? in the "require" - line?

This is my composer.js-file:

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        },
        "magento": {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.0",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.0.6",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}

**Comment by therouv** [comment]
Hi @simadesign To the "repositories" section.

**Comment by simadesign** [comment]
Thanks for your help @therouv :+1: I give it a try!

**Comment by simadesign** [comment]
I add this to the composer.js:

		"firegento-magesetup2": {
		  "type": "git",
		  "url": "https://github.com/firegento/firegento-magesetup2.git"
		}

But the composer update only shows "Nothing to install or update". I also tried "composer require firegento/firegento-magesetup2" there comes: "Could not find package".

**Comment by therouv** [comment]
It should look like this:

```json
  ...
  "repositories": [
    ...
    {
      "type": "git",
      "url": "https://github.com/firegento/firegento-magesetup2.git"
    }
  ],
  ...
```

**Comment by simadesign** [comment]
ok. I'm confused.The composer.js from magento looks like this:

"repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        },
        "magento": {
            "type": "composer",
            "url": "http://packages.magento.com/"
        },
},
