### ISSUE TITLE
PHP Version Check,PHP Extensions Check

### ISSUE THREAD

**Issue by jyotirekhasahoo** [firegento/firegento-magesetup2#20]
Hi,

I was  unable to install firegento-magesetup2.It always throwing these listed errors.
1.PHP Version Check 
But in my server its 5.6 satisfying the recruitment criteria which is >=5.5 
2. PHP Extensions Check
3.PHP Settings Check  

 Not giving the details of which extension and settings are missed.

Any help is appreciated.

Thanks much and best regards,
Jyoti

**Comment by tniebergall** [comment]
Hi,

could you give us the magento version?

**Comment by jyotirekhasahoo** [comment]
Thank you for your review.
I was in magetno 2.0 .Now after upgradation to 2.1 firegento is working.

So i closing this ticket.
