### ISSUE TITLE
magesetup:setup:run stuck at Start processor: tax

### ISSUE THREAD

**Issue by Josch-** [firegento/firegento-magesetup2#201]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 1.0.0.
* Magento version: 2.4.3
* PHP version: 7.3.29

### Issue description

Hi,

I updated to Magento 2.4.3 today. After the upgrade of firegento-magesetup2:

`Upgrading firegento/magesetup2 (v0.4.1 => v1.0.0)`

I did a:

`bin/magento magesetup:setup:run de`

This is the output:

`Start setup
Start processor: agreements
Start processor: cms
Start processor: email
Start processor: systemConfig
Start processor: tax`

And now the process is stuck/does nothing/gives no output?

Any help would be highly appreciated.

### Steps to reproduce

1. take a Magento 2.4.3 installation
2. update firegento-magesetup2 from 0.4.0 to 1.0.0
3. run `bin/magento magesetup:setup:run de`

**Comment by Josch-** [comment]
Wow, after a REALLY long time the setup is (unexpectedly ;-)) finished. So I close this issue. Sorry.

**Comment by sprankhub** [comment]
Hmm I just checked the code of the tax processor, but I could not find anything, which should take such a long time. We do update all products, but with a rather efficient method `\Magento\Catalog\Model\Product\Action::updateAttributes`... How many products do you have?

Anyway, good that it is not a real issue :+1:

**Comment by Josch-** [comment]
Yes, I‘m glad, too that it is not a real issue. To answer your question: we have 3000 products in our shop. Not a very big chunk ;-)
