### ISSUE TITLE
composer install aborts

### ISSUE THREAD

**Issue by stradd** [firegento/firegento-magesetup2#202]
* Magento version: 2.4.2-p2
* PHP version: x7.4

I tried to install magesetup2 with the command:
composer require firegento / magesetup2

The installation aborts with the following error message.

 Problem 1
    - Root composer.json requires firegento/magesetup2 ^1.0 -> satisfiable by firegento/magesetup2[v1.0.0].
    - firegento/magesetup2 v1.0.0 requires magento/framework >=103.0.3 -> found magento/framework[103.0.3, 103.0.3-p1] but the package is fixed to 103.0.2-p2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by sprankhub** [comment]
See https://github.com/firegento/firegento-magesetup2#requirements.

Please try `composer require firegento/magesetup2:"^0.4"`.

**Comment by jkemke** [comment]
Magento version 2.4.3-p1
PHP version 7.4.25
Problem 1
    - Root composer.json requires firegento/magesetup2 ^1.0 -> satisfiable by firegento/magesetup2[v1.0.0].
    - firegento/magesetup2 v1.0.0 requires magento/module-store * -> could not be found in any version, there may be a typo in the package name.

I have tried also
 Problem 1
    - firegento/magesetup2[v0.4.0, ..., v0.4.1] require magento/module-store * -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires firegento/magesetup2 ^0.4 -> satisfiable by firegento/magesetup2[v0.4.0, v0.4.1].

it looks like the same error
