### ISSUE TITLE
Installation abort in Magento version 2.4.3-p1

### ISSUE THREAD

**Issue by jkemke** [firegento/firegento-magesetup2#203]
Magento version 2.4.3-p1
PHP version 7.4.25
  Problem 1
    - Root composer.json requires magento/product-community-edition 2.4.3, found magento/product-community-edition[2.4.3] but the package is fixed to 2.4.3-p1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

10 minutes ago this message appears
Problem 1
    - Root composer.json requires firegento/magesetup2 ^1.0 -> satisfiable by firegento/magesetup2[v1.0.0].
    - firegento/magesetup2 v1.0.0 requires magento/module-store * -> could not be found in any version, there may be a typo in the package name.

I have tried also
 Problem 1
    - firegento/magesetup2[v0.4.0, ..., v0.4.1] require magento/module-store * -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires firegento/magesetup2 ^0.4 -> satisfiable by firegento/magesetup2[v0.4.0, v0.4.1].

it looks like the same error

_Originally posted by @jkemke in https://github.com/firegento/firegento-magesetup2/issues/202#issuecomment-964911952_

**Comment by sprankhub** [comment]
I do not quite follow as you posted multiple problems. To me, the following looks like the actual issue:

> Root composer.json requires magento/product-community-edition 2.4.3, found magento/product-community-edition[2.4.3] but the package is fixed to 2.4.3-p1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Before you require `firegento/magesetup2`, can you please make sure that your Magento instance works as expected? If you had  `firegento/magesetup2` before, try to remove it first. Then, make sure your Magento instance works. Then,run `composer require firegento/magesetup2`.
