### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by caos989** [firegento/firegento-magesetup2#204]
Where can I find the configuration in M2 like in M1?

I installed the extension manually with this coammands now I see the tax text but I'm missing the configuration in the backend?
bin/magento module:enable FireGento_MageSetup
bin/magento setup:upgrade
bin/magento magesetup:setup:run at

**Comment by sprankhub** [comment]
Which configuration do you mean exactly? The steps, where mails, taxes etc. are setup can now only be run via the CLI (see your `magesetup:setup:run at` command). 

Additionally, as you can see in https://github.com/firegento/firegento-magesetup2/blob/develop/etc/adminhtml/system.xml, there is an imprint configuration under "General", a few settings under Catalog > Price and a few under Catalog > Frontend.
