### ISSUE TITLE
Correct version for Magento 2.2.9

### ISSUE THREAD

**Issue by OvalMedia** [firegento/firegento-magesetup2#209]
Hello,

I need to (locally) install an older version of magento (2.2.9). In the composer.json this module is mentioned as `"firegento/magesetup2": "dev-develop"`. When I do a composer install it tries to install the latest version which obviously collides with the magento requirements (php 7.1 for instance).

What would be the proper composer command to install the proper version for 2.2.9?

`composer require firegento/magesetup2:0.4.*` does not work either. It requires at least php 7.2.

**Comment by frostblogNet** [comment]
hello @OvalMedia you can try to check out a specific commit hash. See here https://www.google.com/amp/s/garthkerr.com/using-a-specific-git-commit-hash-for-composer/amp/ for more information

**Comment by OvalMedia** [comment]
`composer require firegento/magesetup2:0.2.*` did the trick.
