### ISSUE TITLE
"Du/Sie"-Wechselbarkeit im Modul?

### ISSUE THREAD

**Issue by grasdaggel** [firegento/firegento-magesetup2#21]
Servus,

wir haben momentan das Problem, dass wir gerne einen Mage2-Shop komplett auf "Du" anstelle von "Sie" haben würden. Gibts im Modul nen Switch dafür, für DACH-Sprachen? Bei anderen Sprachen weiß ich nicht, inwiefern da unterschieden wird.

Gruß

**Comment by damac23** [comment]
M.W. gibt es noch keine "Du"-Variante für Magento2.
Ist auch bei Magento1 eine große Lücke - da kenn ich nur http://www.brainworxx.de/brainlife/2011/05/27/neues-magento-sprachpaket-in-der-du-version/ und das ist schon hoffnungslos alt.

**Comment by therouv** [comment]
Hi @grasdaggel leider ist die Übersetzung nicht Bestandteil von MageSetup. Vllt. kannst Du es ja einmal hier einbringen: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE
