### ISSUE TITLE
shouldAddPriceDetails() to public

### ISSUE THREAD

**Issue by Cloudy777** [firegento/firegento-magesetup2#210]
### General

* Module version: v1.1.2

### Issue description

Would it be possible to change Plugin/Pricing/AddPriceDetailsPlugin.php::shouldAddPriceDetails() from private to public? 
We want to modify when the price details are rendered (some product don't need them).
A plugin here would be the best way imo. We can do a pull request if needed.
What do you think?

**Comment by frostblogNet** [comment]
Hello @Cloudy777 

there is no reason why this method is private so a pull request would be nice.

Thanks

**Comment by frostblogNet** [comment]
Thanks for contribution.
