### ISSUE TITLE
Magento 2.4.6-p1 partially supported

### ISSUE THREAD

**Issue by Moppelfett** [firegento/firegento-magesetup2#219]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 1.2.1
* Magento version: 2.4.6-p1
* PHP version: 8.1.x

### Issue description
"incl. VAT plus shipping costs" are only shown in the Grid and List view, but not on the product page.

### Steps to reproduce

1. Install Magento 2.4.6-p1
2. Install Firegento

**Comment by sprankhub** [comment]
I just tested this on 2.4.6-p1 and it works fine on my demo instance:

![image](https://github.com/firegento/firegento-magesetup2/assets/930199/0d08ca57-8360-469f-9c3c-6d9f46ddc255)

Make sure you have enabled `catalog/price/display_block_below_price`.

If it does not work for you, you might want to debug into `\FireGento\MageSetup\Plugin\Pricing\AddPriceDetailsPlugin::afterRender`.
