### ISSUE TITLE
After Update via Composer main.CRITICAL: Error: Call to a member function getStoreLabel()

### ISSUE THREAD

**Issue by beendeluxe** [firegento/firegento-magesetup2#220]
Hey, we are facing an issue described below. Hope to get some help to solve it.

### General

* Module version: 1.2.^
* Magento version: 2.4.5-p3
* PHP version: 8.1.21

### Issue description
After updating to Magento 2.4.5-p3 and to Firegento 1.2.1 we are facing this issue. When opens a product on product view the error appears;
main.CRITICAL: Error: Call to a member function getStoreLabel() on bool in /vendor/magento/module-catalog/view/frontend/templates/product/view/attribute.phtml:1

### Steps to reproduce

1. update extension to latest version via composer
2. run magesetup:setup:run de
3. Upgrade, compile, deploy, flush cache
4. visit website, visit any product
5.  An error has happened during application run. See exception log for details.
6. Exception log: main.CRITICAL: Error: Call to a member function getStoreLabel() on bool in /vendor/magento/module-catalog/view/frontend/templates/product/view/attribute.phtml:1

Any Idea how to fix it?

Thanks for any help.

We had to deactivate this extension for now. Without this extension, everything is working as expected. Hope to get help here so we can reactivate it.

~Beendeluxe

**Comment by sprankhub** [comment]
In general, the module works with Magento 2.4.5-p3, so this seems to be store-specific. I think this can only happen if the `delivery_time` attribute has mistakenly be deleted from the store. Could you check if it exists and if not, create it again? We add it to the product page in https://github.com/firegento/firegento-magesetup2/blob/develop/view/frontend/layout/catalog_product_view.xml.
