### ISSUE TITLE
Support of PHP 8.3

### ISSUE THREAD

**Issue by wilfriedwolf** [firegento/firegento-magesetup2#221]
Are there Plans to support PHP 8.3, is there more to it than altering composer.json?

### General

* Module version: 1.2.1
* Magento version: 2.4.7
* PHP version: 8.3.6

### Issue description
Trying to update magento shop with PHP 8.3 results in:
```

Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - firegento/magesetup2 v1.2.0 requires php ~7.3.0||~7.4.0||~8.1.0 -> your php version (8.3.6) does not satisfy that requirement.
    - firegento/magesetup2 v1.2.1 requires php ~7.3.0||~7.4.0||~8.1.0||~8.2.0 -> your php version (8.3.6) does not satisfy that requirement.
    - Root composer.json requires firegento/magesetup2 ^1.2 -> satisfiable by firegento/magesetup2[v1.2.0, v1.2.1].
```

### Steps to reproduce

1. Install Magento 2.4.7 with `firegento/magesetup2` and PHP 8.2
2. Try to upgrade using `composer update` with PHP 8.3

**Comment by sprankhub** [comment]
Most probably, it is enough to update `composer.json`. Could you test this and send a PR? That would be great.

**Comment by jg-development** [comment]
added pull request
