### ISSUE TITLE
Checkbox2 at Checkout not required

### ISSUE THREAD

**Issue by johwebserv** [firegento/firegento-magesetup2#29]
Hello,

we have a fresh install of the german-checkout with magesetup2. The second checkbox for "Widerrufsbelehrung" isn't required but in the source it is:

`<div class="checkout-agreement">
                <input type="checkbox" data-bind="attr: {
                                    'id': 'agreement_' + agreementId,
                                    'name': 'agreement[' + agreementId + ']',
                                    'value': agreementId
                                    }" data-validate="{required:true}" id="agreement_2" name="agreement[2]" value="2">
                <label data-bind="attr: {'for': 'agreement_' + agreementId}" for="agreement_2">
                    <button type="button" class="action action-show" data-bind="click: function(data, event) { return $parent.showContent(data, event) }">
                        <span data-bind="html: checkboxText">Ich habe die Widerrufsbelehrung gelesen.</span>
                    </button>
                </label>
            </div>`

The User can submit the checkout-form when the first checkbox "AGB" is checked.

**Comment by frostblogNet** [comment]
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks
