### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by mpan2014** [firegento/firegento-magesetup2#3]
Hello,

I've been tryin to install the module so I copied the whole zip to \app\code\FireGento\MageSetup. After that I enabled the module, updated the database and refreshed the cache. But I can see no changes. 
How can I configure the module?

Regards
Marco

**Comment by davidverholen** [comment]
Hi Marco,

are you sure that the module is active? There Should be at least the imprint group in the Store General Configuration.

As far as I know you have to install the modules via composer because it executes the registration.php in the bootstrap process, where the Module is registered in the Magento ComponentRegistrar.

**Comment by damac23** [comment]
I've installed it via composer with
<pre>
"firegento/magesetup2": "dev-develop"
</pre>
plus den Repo-Verweis, weil es noch keine Release gibt:
<pre>
    "repositories": [
        {
        "type": "vcs",
        "url": "https://github.com/firegento/firegento-magesetup2"
        }
    ],
</pre>

I cannot see any option like "imprint" group within STORES > Configuration > General.
I'm using the the latest DEV-Version of Magento 2.0.0 as of today.

**Comment by davidverholen** [comment]
you also need to run bin/magento setup:upgrade to activate the module after installing.
then look under store -> configuration -> advanced -> advanced if the module is active

**Comment by damac23** [comment]
Thanks - I can see the group now.
But the plugin isn't ready yet for generating tax rules and stuff, right?

**Comment by davidverholen** [comment]
yes, seems like there are still some things missing.

@therouv would it be possible to collect a list of missing (wanted) features to encourage contributing?

**Comment by therouv** [comment]
@damac23 Tax rules for Germany is already implemented. Other countries will follow.

@davidverholen I can try to create a list with the missing features in the beginning of the next year. Please note that not all functionality from `MageSetup for M1` will be ported because M2 already implements them.

**Comment by damac23** [comment]
@therouv thanks!

**Comment by davidverholen** [comment]
nice, thanks

**Comment by developer-lindner** [comment]
A configuration notice would be very helpful!

I've just installed the module via composer, upgraded the magento setup and had a look into the backend, but i can't find any tax rules for Germany. So how do we use it?

**Comment by davidverholen** [comment]
theres a console command for executing the setup. bin/magento magesetup:setup:run.

However, i had problems today executing the command in production mode with di compiled resulting in an error. When I find the time to reproduce it I'll create an issue. For me activating developer mode and removing the var/di folder did the trick

**Comment by developer-lindner** [comment]
ah okay, that's exactly what's missing in the readme.md!
Thanks for the hint!

**Comment by therouv** [comment]
@davidverholen It should work now with compiled DI configuration.

**Comment by frostblogNet** [comment]
I think this issue is solved. If not feel free to  reopen it.

Thanks
