### ISSUE TITLE
Konfigure general_locale_weight_unit

### ISSUE THREAD

**Issue by riker09** [firegento/firegento-magesetup2#31]
After setting up a default Magento 2 store for the first time (yay!) I've noticed that the product weight had to be specified in `lbs`. Then after looking in the system configuration I found the related setting field, `general_locale_weight_unit`, and indeed, it was set to `lbs`.

IMHO after running `magento magesetup:setup:run de` this field value should be `kgs`. What do you think?

**Comment by therouv** [comment]
@riker09 Makes sense. Can you provide a pull request? I'd be happy to merge it :-)

**Comment by frostblogNet** [comment]
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks

**Comment by sprankhub** [comment]
I think we should check if this is still an issue and only close if it is fixed.

**Comment by riker09** [comment]
Huh, I totally forgot about this issue. Sorry about that. I have switched moved away from Magento for professional reasons (new company).

**Comment by BorisovskiP** [comment]
This issue is still  present in version v0.2.0 of the module. If the store is firstly set to locale:US and Weight Unit : lbs, running `bin/magento magesetup:setup:run de` does not change the local nor the weight units
