### ISSUE TITLE
first release

### ISSUE THREAD

**Issue by davidverholen** [firegento/firegento-magesetup2#32]
Hey, would it be possible, to make at least a first beta release? This way, people already using the extension could be sure not to pull in every change from the develop branch

**Comment by DavidLambauer** [comment]
+1 for a release

**Comment by DavidLambauer** [comment]
Any Updates on this issue?

**Comment by mautz-et-tong** [comment]
Your wish is my command:
https://github.com/firegento/firegento-magesetup2/releases/tag/v0.1.0
