### ISSUE TITLE
Checkout confirmation block for business terms and revocation

### ISSUE THREAD

**Issue by Raphomee** [firegento/firegento-magesetup2#37]
Hi,

in checkout when I click on the text to read business terms or revocation only a layer with the following content opens:
### 

{{block class="Magento\Cms\Block\Block" block_id="business_terms"}}
### 

and
### 

{{block class="Magento\Cms\Block\Block" block_id="revocation"}}
### 

Blocks are added in Backend, Cache cleared etc.

Kind regards,
Raphael Gehlhaar

**Comment by grillpro** [comment]
This would be interesting for us, too. We have the same problem. Magento 2.1, The Business-Terms are correctly at https://www.roesle-grillshop.de/agb/

![business-terms](https://cloud.githubusercontent.com/assets/21044102/17675747/62584a7a-632b-11e6-89c2-9f7ac738954b.JPG)

Does anybody have an idea? Thank you very much for your help!

**Comment by grillpro** [comment]
So, to solve the problem quick and dirty I have put the business-terms and revocation-terms by copy and paste at the admin to menue: shops, configuration, business-terms. 

If somebody wants to solve the main problem, because my way is not the way it should work (I think) - I HAVE PUT THE CODE FOR THE STATIC BLOCK TO THE BOTTOM BELOW MY COPY+PASTE-TEXT.

**Comment by therouv** [comment]
Hi @Raphomee @grillpro 
I just installed a clean Magento2 2.1.0 instance with FireGento. The MageSetup agreements show up correctly. Even after I changed the contents of the static block.

Can you provide more information like Magento version, PHP version, etc.?

**Comment by Raphomee** [comment]
Hi,

using grillpros workaround right now.
Maybe its meant to be work this way and its just a bit distracting becaused I thought the CMS-Block is used instaed of this additional configuration option?

Magento-Version: 2.1.0 (upgraded from 2.0.x)
PHP-Version: 7.0.9

**Comment by frostblogNet** [comment]
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks
