### ISSUE TITLE
Incorrect dependency in /vendor/firegento/magesetup2/Block/Imprint/Content.php

### ISSUE THREAD

**Issue by tecjam** [firegento/firegento-magesetup2#4]
Hi there, I installed Magento2 via composer. I then added Firegento-magesetup2 via composer:
In the composer.json:

        "repositories": [
            (...)
            {
                "type": "vcs",
                "url": "https://github.com/firegento/firegento-magesetup2"
            }
        ],
        "require": {
            (..)
            "firegento/magesetup2": "dev-develop",

Installation worked - backend settings for Imprint are available

Then when compiling using 'php bin/magento deploy:mode:set production' I receive the following error:

        Errors during compilation:
        
                FireGento\MageSetup\Block\Imprint\Content
        
                Incorrect dependency in class FireGento\MageSetup\Block\Imprint\Content in /vendor/firegento/magesetup2/Block/Imprint/Content.php
        
                \Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
        
        Total Errors Count: 1

**Comment by therouv** [comment]
Fixed in #5
