### ISSUE TITLE
no translations with Magento 2.1

### ISSUE THREAD

**Issue by thomas-villagers** [firegento/firegento-magesetup2#40]
Hi there,

is firegento-magesetup2 compatible with magento 2.1? 

I'm asking because I followed the installation instructions and it seems to pull files from the correct locale dir (/pub/static/frontend/Magento/luma/de_DE/ in my case according to apache2/access.log), but frontend and backend are still in English. Default Country, Locale and Store Country are "German". Cache is flushed and cleared, indexes are rebuilt. 

any ideas? 

- thanks, thomas

**Comment by therouv** [comment]
Hi @thomas-villagers - MageSetup2 does not provide the German translation, just the necessary configuration for the German market.

**Comment by thomas-villagers** [comment]
ah ok, thanks for clarifying! :-)
