### ISSUE TITLE
No Color Swatches on Category List Page after magesetup 2 installation

### ISSUE THREAD

**Issue by casensky** [firegento/firegento-magesetup2#42]
Hi,

when I install magesetup 2 on a new Magento 2.1.1 installation and add a configurable Product with Color Swatches, the Swatches are not visible on the Category List Page. On the Product Detail Page the Swatches work as expected. When I disable the magesetup 2 Module then the Swatches are also working on the Category Page. Any Ideas what is happening and how to fix it?

best regards
Christian Casensky

**Comment by bka** [comment]
Same issue here. I created a PR which fixes this for me.

**Comment by dakira** [comment]
@mautz-et-tong this can be closed. Fixed with PR.
