### ISSUE TITLE
Error on category page ... ListProductPlugin.php on line 37

### ISSUE THREAD

**Issue by Anis108** [firegento/firegento-magesetup2#45]
On cotegory page I have this error after installing the magesetup 2.

Can somebody give a hint how to solve it or how to uninstall it?

Fatal error: Uncaught Error: Call to a member function setProduct() on boolean in /.../app/code/FireGento/MageSetup/Plugin/Catalog/ListProductPlugin.php:37 Stack trace: #0 /..../vendor/magento/framework/Interception/Interceptor.php(142): FireGento\MageSetup\Plugin\Catalog\ListProductPlugin->aroundGetProductDetailsHtml(Object(Magento\Catalog\Block\Product\ListProduct\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor)) #1 /..../var/generation/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(442): Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins('getProductDetai...', Array, Array) #2 /.../design/frontend/Smartwave/porto/Magento_Catalog/templates/product/list.phtml(215): Magento\Catalog\Block\Product\ListProduct\Interceptor->getProductDetailsHtml(Object(Magento\Catalog\Model\Product\Interceptor)) #3 /... in /.../app/code/FireGento/MageSetup/Plugin/Catalog/ListProductPlugin.php on line 37

**Comment by eisfair** [comment]
Well, i guess the existing pull request #39 may be something you are looking for.

**Comment by therouv** [comment]
Fixed with merge of PR #39
