### ISSUE TITLE
Block\Price\Details caches product VAT on category/list view

### ISSUE THREAD

**Issue by josefbehr** [firegento/firegento-magesetup2#46]
The Price Detail Block for details.phtml shows the same VAT percentage for all products on category or list view. This seems to be due to the _getFormattedTaxRate()_ method checking that 'tax_rate' is in the block's data array, at the same time not making sure that the _saleableItem_, which's VAT it should display, has changed. Therefore, two or more products belonging to different VAT classes always show a value depending on the first one.

To reproduce, add one product to reduced VAT class and another to full VAT class and show them both on the category page. Set a break point in line 89 of Details.php to see that on the first product, VAT is correctly calculated, but on the second one, the set tax rate from the first product will be used, although _$this->saleableItem_ has changed to the new one. 

![screen shot 2016-10-26 at 17 36 38](https://cloud.githubusercontent.com/assets/4368880/19733013/001a2800-9ba3-11e6-9ca9-1a870305b9e5.png)
![screen shot 2016-10-26 at 17 36 52](https://cloud.githubusercontent.com/assets/4368880/19733014/00251fb2-9ba3-11e6-83ae-7d07bff18bf3.png)

**Comment by josefbehr** [comment]
Nothing? Do you need more information? Is it not reproducable? We're on Magento 2.1.2 btw...

**Comment by therouv** [comment]
Related PR is merged.
