### ISSUE TITLE
No valid composer.json was found in any branch or tag of https://github.com/firegento/firegento-magesetup2.git, could not load a package from it.

### ISSUE THREAD

**Issue by michaelberg79** [firegento/firegento-magesetup2#47]
Hi, I installed the extention how descriped at readme. The installation runs fine. Now i try to open the component overview in the setup area of magento 2. 
The page cant be loaded because of following error:
No valid composer.json was found in any branch or tag of https://github.com/firegento/firegento-magesetup2.git, could not load a package from it.
How i am able to solve this problem?

best regards
Michael Berg

**Comment by strebelweb** [comment]
Hi
same problem here. 
Do you have any solution for this?

thank's and best regards,
Chris

**Comment by therouv** [comment]
Hi @michaelberg79 @strebelweb 
Please use "dev-develop" in your composer.josn for now:

```json
{
    ...
    "require": {
        ...
        "firegento/magesetup2": "dev-develop"
    },
    ...
}
```

In dev-master there is currently no composer.json which will change after the first version is tagged and released.

**Comment by strebelweb** [comment]
hi therouv

thank's for you comment. 
i still use this: "firegento/magesetup2": "dev-develop",

any other solution?

thank's

**Comment by raymond62** [comment]
Same issue ...

```
RuntimeException

File:

    /var/www/vhosts/loverice.eu/httpdocs/setup/src/Magento/Setup/Model/PackagesData.php:88

Message:

    Command "show" failed: 

                                                                                                                                                     
      [Composer\Repository\InvalidRepositoryException]                                                                                               
      No valid composer.json was found in any branch or tag of git@github.com:firegento/firegento-magesetup2.git, could not load a package from it.  
```

Is there any solution?

**Comment by pixxet** [comment]
why is this issue closed if there is no solution for it?
