### ISSUE TITLE
Asymmetric transaction rollback.

### ISSUE THREAD

**Issue by sync2013** [firegento/firegento-magesetup2#48]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: x.x.x
* Magento version: 2.1.2
* PHP version: 5.6.27

### Issue description
module us installed succesfully, by running 
bin/magento magesetup:setup:run de
Start setup
Start processor: agreements
Start processor: cms
Start processor: email
Start processor: systemConfig
Start processor: tax
Asymmetric transaction rollback.
/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(99): Magento\Framework\DB\Adapter\Pdo
Mysql->rollBack()
#1 /var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(791): Magento\Framework\Mode
\ResourceModel\AbstractResource->rollBack()
#2 /vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(57): Magento\Catalog\Mod
l\ResourceModel\Product\Interceptor->rollBack()
.......

except for country code de,  if i try others countries, like at, ch, all listed countries code are installed succesfully

### Steps to reproduce

1. ... 
2. ... 
3. ...

**Comment by morfij** [comment]
Hi, I have same issue.

- Magento version: 2.1.6
- PHP version: 5.6.30

**Comment by mautz-et-tong** [comment]
Hi @sync2013,
Could you (both) please deliver more information like:
- other modules installed
- which branch
- and so on
By now, I am not able to reproduce this behaviour.

**Comment by morfij** [comment]
Accidentally I solved this issue. Just make reindex. Run in command line:
_bin/magento indexer:reindex_
it helped me.

**Comment by BorisovskiP** [comment]
Tested on Magento Version : 2.3.5-p1, module version0.2.0, the issue could not be reproduced.
