### ISSUE TITLE
Display of VAT not working for grouped products

### ISSUE THREAD

**Issue by jaykobi** [firegento/firegento-magesetup2#56]
### General

* Module version: latest (464f2ce)
* Magento version: 1.2.1
* PHP version: 7.0.1

### Issue description

For Simple Products VAT is corrcetly shown on item details page. However for a groupd product VAT is 0 for total price and all individual prices. I have grouoed products with different VATs.

**Comment by sagacitysite** [comment]
Same problem here using configurable product. VAT is always zero.

Did you find a solution for that?

**Comment by jghaanstra** [comment]
I have created a very small extension which fixes this specific issue for grouped products. You can install it to fix this issue until it is fixed in Magento core.

https://github.com/jghaanstra/magento-grouped-product-tax-fix

**Comment by grossmann** [comment]
Hi, according to Magento team it should already be fixed since Magento 2.2 (https://github.com/magento/magento2/issues/8214#issuecomment-335175791).
But I still experience this in a Magento 2.3.3 install. Can someone confirm this is still an open issue?

**Comment by frostblogNet** [comment]
In the current version there is no longer a tax displaded on the goruped product. So in my option this issue is closed. But if I get something wrong, please reopen it agian. 

Thanks
