### ISSUE TITLE
seems to ignore the scope (multishop)

### ISSUE THREAD

**Issue by pwtanagit** [firegento/firegento-magesetup2#60]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: x.x.x (fresh from git -- where to see the version?)
* Magento version: 2.1.3
* PHP version: 7.0.13

### Issue description
- {{block class="FireGento\MageSetup\Block\Imprint\Field" field="shop_name"}} does not care for the scope
- set different values under "impress" e.g. for "shop name" for "default"-scope, "website 1"-scope and "storeview2"-scope
- if calling the block class, field name "shop name" it will always lookup at "default"-scope

### Steps to reproduce

1. fresh 2.1.3 install (no demo data)
2. fresh firegento via composer
3. add second website (and store and view)
4. fill impress
5. link impress page to home-page of 2nd website

**Comment by frostblogNet** [comment]
Currently magesetup2 is not able to handle multi store setup. There is allready an issue for this #36 so I will close this one.
