### ISSUE TITLE
Magento2 German Package

### ISSUE THREAD

**Issue by bucka46** [firegento/firegento-magesetup2#63]
Hi there, 
i just tried to install the german language pack "firegento-magesetup2-develop" via ssh and got a Problem. My issue says: 

Frontend:
Plugin class FireGento\MageSetup\Plugin\Catalog\ListProductPlugin doesn't exist

Backend: 
Object DOMDocument should be created.

`Requested languages: de_DE
Requested areas: frontend, adminhtml
Requested themes: Magento/blank, Magento/luma, Sm/revo, Magento/backend
=== frontend -> Sm/revo -> de_DE ===
=== adminhtml -> Magento/backend -> de_DE ===
=== frontend -> Magento/luma -> de_DE ===
=== frontend -> Magento/blank -> de_DE ===
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2137 files; errors: 0
---

................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2075 files; errors: 0
---

....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2460 files; errors: 2
---

.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Successful: 2062 files; errors: 0
---

=== Minify templates ===

Successful: 995 files modified
---

New version of deployed files: 1486720437
web-user@:~/dev.ktm-powerversand.de/htdocs$ php bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/var/www/share/dev.ktm-powerversand.de/htdocs/var/generation/Composer
/var/www/share/dev.ktm-powerversand.de/htdocs/var/generation/Magento
/var/www/share/dev.ktm-powerversand.de/htdocs/var/generation/Sm
/var/www/share/dev.ktm-powerversand.de/htdocs/var/generation/Symfony
The directory '/var/www/share/dev.ktm-powerversand.de/htdocs/var/di/' doesn't exist - skipping cleanup
/var/www/share/dev.ktm-powerversand.de/htdocs/pub/static/_requirejs
/var/www/share/dev.ktm-powerversand.de/htdocs/pub/static/adminhtml
/var/www/share/dev.ktm-powerversand.de/htdocs/pub/static/deployed_version.txt
/var/www/share/dev.ktm-powerversand.de/htdocs/pub/static/frontend
/var/www/share/dev.ktm-powerversand.de/htdocs/var/view_preprocessed/css
/var/www/share/dev.ktm-powerversand.de/htdocs/var/view_preprocessed/html
/var/www/share/dev.ktm-powerversand.de/htdocs/var/view_preprocessed/source
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Theme':
Module 'Magento_Eav':
Module 'Magento_Backup':
Module 'Magento_Customer':
Module 'Magento_AdminNotification':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Msrp':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'FireGento_MageSetup':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_SalesSequence':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Bundle':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_CatalogInventory':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Checkout':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_CatalogRule':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_GoogleAdwords':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_Paypal':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Sm_BasicProducts':
Module 'Sm_Cartpro':
Module 'Sm_Categories':
Module 'Sm_Deals':
Module 'Sm_ImageSlider':
Module 'Sm_InstagramGallery':
Module 'Sm_ListingDeals':
Module 'Sm_ListingExtend':
Module 'Sm_ListingTabs':
Module 'Sm_MegaMenu':
Module 'Sm_QuickView':
Module 'Sm_Revo':
Module 'Sm_SearchBox':
Module 'Sm_ShopBy':
Module 'Sm_SuperCategories':
Schema post-updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Theme':
Module 'Magento_Eav':
Module 'Magento_Backup':
Module 'Magento_Customer':
Module 'Magento_AdminNotification':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Running schema recurring...
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Running schema recurring...
Module 'Magento_Rule':
Module 'Magento_Msrp':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'FireGento_MageSetup':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_SalesSequence':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Bundle':
Running schema recurring...
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_CatalogInventory':
Running schema recurring...
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Checkout':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Running schema recurring...
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Running schema recurring...
Module 'Magento_ProductVideo':
Module 'Magento_CatalogRule':
Module 'Magento_Reports':
Running schema recurring...
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_GoogleAdwords':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Running schema recurring...
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_Paypal':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Running schema recurring...
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Running schema recurring...
Module 'Sm_BasicProducts':
Module 'Sm_Cartpro':
Module 'Sm_Categories':
Module 'Sm_Deals':
Module 'Sm_ImageSlider':
Module 'Sm_InstagramGallery':
Module 'Sm_ListingDeals':
Module 'Sm_ListingExtend':
Module 'Sm_ListingTabs':
Module 'Sm_MegaMenu':
Module 'Sm_QuickView':
Module 'Sm_Revo':
Module 'Sm_SearchBox':
Module 'Sm_ShopBy':
Module 'Sm_SuperCategories':
DDL cache cleared successfully
Data install/update:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Theme':
Module 'Magento_Eav':
Module 'Magento_Backup':
Module 'Magento_Customer':
Module 'Magento_AdminNotification':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Msrp':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'FireGento_MageSetup':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_SalesSequence':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Bundle':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_CatalogInventory':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Checkout':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_CatalogRule':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_GoogleAdwords':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_Paypal':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Sm_BasicProducts':
Module 'Sm_Cartpro':
Module 'Sm_Categories':
Module 'Sm_Deals':
Module 'Sm_ImageSlider':
Module 'Sm_InstagramGallery':
Module 'Sm_ListingDeals':
Module 'Sm_ListingExtend':
Module 'Sm_ListingTabs':
Module 'Sm_MegaMenu':
Module 'Sm_QuickView':
Module 'Sm_Revo':
Module 'Sm_SearchBox':
Module 'Sm_ShopBy':
Module 'Sm_SuperCategories':
Data post-updates:
Module 'Magento_Store':
Module 'Magento_Directory':
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Backend':
Module 'Magento_Theme':
Running data recurring...
Module 'Magento_Eav':
Module 'Magento_Backup':
Module 'Magento_Customer':
Module 'Magento_AdminNotification':
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Module 'Magento_Rule':
Module 'Magento_Msrp':
Module 'Magento_Search':
Module 'Magento_CatalogUrlRewrite':
Module 'Magento_Widget':
Module 'Magento_Quote':
Module 'Magento_CheckoutAgreements':
Module 'FireGento_MageSetup':
Module 'Magento_CmsUrlRewrite':
Module 'Magento_Config':
Module 'Magento_ConfigurableImportExport':
Module 'Magento_SalesSequence':
Module 'Magento_Contact':
Module 'Magento_Cookie':
Module 'Magento_Cron':
Module 'Magento_CurrencySymbol':
Module 'Magento_Payment':
Module 'Magento_CustomerImportExport':
Module 'Magento_Deploy':
Module 'Magento_Developer':
Module 'Magento_Dhl':
Module 'Magento_Authorization':
Module 'Magento_Downloadable':
Module 'Magento_ImportExport':
Module 'Magento_Bundle':
Module 'Magento_Email':
Module 'Magento_User':
Module 'Magento_Fedex':
Module 'Magento_Sales':
Module 'Magento_CatalogInventory':
Module 'Magento_GoogleAnalytics':
Module 'Magento_Ui':
Module 'Magento_GroupedImportExport':
Module 'Magento_GroupedProduct':
Module 'Magento_DownloadableImportExport':
Module 'Magento_Checkout':
Module 'Magento_Security':
Module 'Magento_LayeredNavigation':
Module 'Magento_Marketplace':
Module 'Magento_MediaStorage':
Module 'Magento_ConfigurableProduct':
Module 'Magento_Multishipping':
Module 'Magento_NewRelicReporting':
Module 'Magento_Newsletter':
Module 'Magento_OfflinePayments':
Module 'Magento_SalesRule':
Module 'Magento_PageCache':
Module 'Magento_Captcha':
Module 'Magento_Vault':
Module 'Magento_Persistent':
Module 'Magento_ProductAlert':
Module 'Magento_ProductVideo':
Module 'Magento_CatalogRule':
Module 'Magento_Reports':
Module 'Magento_RequireJs':
Module 'Magento_Review':
Module 'Magento_Rss':
Module 'Magento_CatalogRuleConfigurable':
Module 'Magento_Authorizenet':
Module 'Magento_SalesInventory':
Module 'Magento_OfflineShipping':
Module 'Magento_GoogleAdwords':
Module 'Magento_SampleData':
Module 'Magento_CatalogSearch':
Module 'Magento_Integration':
Module 'Magento_SendFriend':
Module 'Magento_Shipping':
Module 'Magento_Sitemap':
Module 'Magento_Paypal':
Module 'Magento_Swagger':
Module 'Magento_Swatches':
Module 'Magento_SwatchesLayeredNavigation':
Module 'Magento_Tax':
Module 'Magento_TaxImportExport':
Module 'Magento_GiftMessage':
Module 'Magento_Translation':
Module 'Magento_GoogleOptimizer':
Module 'Magento_Ups':
Module 'Magento_UrlRewrite':
Module 'Magento_EncryptionKey':
Module 'Magento_Usps':
Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Sm_BasicProducts':
Module 'Sm_Cartpro':
Module 'Sm_Categories':
Module 'Sm_Deals':
Module 'Sm_ImageSlider':
Module 'Sm_InstagramGallery':
Module 'Sm_ListingDeals':
Module 'Sm_ListingExtend':
Module 'Sm_ListingTabs':
Module 'Sm_MegaMenu':
Module 'Sm_QuickView':
Module 'Sm_Revo':
Module 'Sm_SearchBox':
Module 'Sm_ShopBy':
Module 'Sm_SuperCategories':
Please re-run Magento compile command
web-user@:~/dev.ktm-powerversand.de/htdocs$ rm -rf var/di
web-user@:~/dev.ktm-powerversand.de/htdocs$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiBPHP Fatal error:  Interface 'FireGento\MageSetup\Model\Setup\SubProcessor\SubProcessorInterface' not found in /var/www/share/dev.ktm-powerversand.de/htdocs/app/i18n/splendid/de_DE/Model/Setup/SubProcessor/AbstractSubProcessor.php on line 15`

* Module version:firegento-magesetup2-develop
* Magento version: 2.1.3
* PHP version: 7.0

Does anyone has an idea? 

Regards

**Comment by splendidinternet** [comment]
@bucka46 

already tried ?

https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE

there are hints for installing magesetup2 and german locale via composer - should work

**Comment by frostblogNet** [comment]
I will close this issue for now because @splendidinternet provides a valid solution.
Thanks
