### ISSUE TITLE
No translation for additional attributes/custom options

### ISSUE THREAD

**Issue by TKlement** [firegento/firegento-magesetup2#64]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: HashId 8165f6a69285d6ea6f534753fdd9e6d2439dc62d
* Magento version: 2.1.2
* PHP version: 7.0.15

### Issue description

We use a custom product attribute that get input by an input field on the product page.
In the table "catalog_product_entity_varchar" I can see the correct translation for the different store_ids.

### Steps to reproduce

1. go to product attributes
2. select attribute
3. set "is visible on checkout" to yes
4. save attribute
5. go to product and fill in different values for that attribute in different store views
6. save product
7. in the frontend got to product and add to cart
8. go to cart
9. that product attribute is now visible on cart
10. change language
11. compare product attribute with that value from before

**Comment by sprankhub** [comment]
Thanks for the good report! I cannot reproduce this with the latest version in Magento 2.3.
