### ISSUE TITLE
How to configure? No new features after installation.

### ISSUE THREAD

**Issue by rorou** [firegento/firegento-magesetup2#65]
Hello,

I have already read issue #3 but did not come to a conclusion. https://github.com/firegento/firegento-magesetup2/issues/3
I did the "manual" installation like the readme told me to do for Austria. No problems, no errors.
I can see the module is active under store -> configuration -> advanced -> advanced.

But I can't see any tax rules or settings, mail templates or option like the "imprint" page. Can you please help me out.

* Module version: downloaded yesterday
* Magento version: 2.1.4 without sample data, clean fresh installation
* Extensions/Lang-Packs installed: German language pack (https://github.com/Magenerds/de_de/releases)
* PHP version: 7.0.13

Thx in advance for your support!

Regards
Roland

**Comment by therouv** [comment]
Hi @rorou thanks for your feedback!
Unfortunately not all settings for AT have been migrated from MageSetup1 yet. That's why there is currently no error and no visual change.

**Comment by rorou** [comment]
I see. Thx for your feedback!

**Comment by mautz-et-tong** [comment]
at as config option is now available

**Comment by rorou** [comment]
Thx for info!
