### ISSUE TITLE
Which type of Argument is it?

### ISSUE THREAD

**Issue by DavidLambauer** [firegento/firegento-magesetup2#7]
Hey, I was just trying to run Magesetup but it didnt work. Im not sure, if Im doing it correctly. I was 

When firing the console command: 
magesetup:setup:run 

I need to add the argument country. Im not sure what to add here. I tried several possibilities like DE, de_DE, Germany, #IWANTTOSETUPUPAFUCKINGGERMANSTORE but nothing worked for me. I just had a tiny look in the code but I was not able to understand the magic behind all the Magneto2 stuff yet. 

May you can give me a little hint, so im able to catch up?

Biggest Thanks

**Comment by therouv** [comment]
Hi @DavidLambauer please try running `php -f bin/magento magesetup:setup:run de`.

**Comment by DavidLambauer** [comment]
Hey @therouv, thanks for the fast reply. I already tried the php -f. The Output is an exception with the following message:

Undefined index: arguments

**Comment by therouv** [comment]
@DavidLambauer Can you try `./bin/magento magesetup:setup:run de" without the php?

**Comment by DavidLambauer** [comment]
./bin/magento magesetup:setup:run de works for me. Thanks!
