### ISSUE TITLE
catalog/price/cms_page_shipping cannot be managed under store view or website

### ISSUE THREAD

**Issue by DavidLambauer** [firegento/firegento-magesetup2#71]
### General

* Module version: develop (there is no release)
* Magento version: 2.1.4
* PHP version: 7.0.13

### Issue description

It is not possible to manage the store configurations for catalog/price/cms_page_shipping and other configurations under the Section "Price". The "Price" Section is defined globally. Due to that, it is not possible to configure the specific config-values on different scopes than global. This causes the effect, that there is no link for the shipping and payment description under the displayed price. 

It should be fixed by moving the system configuration flags to another place where they aren't dependent by the Price Category itself.

### Steps to reproduce

1. Add 2 Stores
2. Install Module
3. Configure Default Config as shown in the Screenshot
<img width="1356" alt="screenshot at marz 20 16-28-33" src="https://cloud.githubusercontent.com/assets/1841317/24107162/55b82d08-0d8a-11e7-919c-96a249ddcc09.png">

<img width="1222" alt="screenshot at marz 20 16-29-43" src="https://cloud.githubusercontent.com/assets/1841317/24107233/7b88795c-0d8a-11e7-8d67-c5f9ac62869a.png">
<img width="1224" alt="screenshot at marz 20 16-30-50" src="https://cloud.githubusercontent.com/assets/1841317/24107276/99c0011a-0d8a-11e7-8498-341ac2d3d2ef.png">

**Comment by therouv** [comment]
Hi @DavidLambauer do you use the current develop branch? 
This bug should have been fixed by commit 658826b

**Comment by DavidLambauer** [comment]
HI @therouv,

Thanks for the hint, we're not using the latest version in production. I'll close this issue.
