### ISSUE TITLE
$_attributeLabel is none, on the product page there is translation "Keine"

### ISSUE THREAD

**Issue by tirgil61** [firegento/firegento-magesetup2#75]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: @dev
* Magento version: 2.1.5
* PHP version: 7.0.7.

### Issue description

On the product page there is no value for the short description for example. Normally the script should skip this attribute. Because of the translation this not happened. 

The variable 
$_attributeLabel = "none"

Because of the translation, the $_attributeLabel is transleted to "Keine" (this is for German language)

$_attributeLabel = "Keine"

Now in the script 

/vendor/module-catalog/view/frontend/templates/product/view/attribute.phtml

the variable $_attributeLabel is checked in ine 37

`<?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>`

Because of $_attributeLabel = 'Keine' the script writes on the product page "Keine".

...

### Steps to reproduce

1. ... 
2. ... 
3. ...

**Comment by sprankhub** [comment]
I am not totally sure if I understand the issue correctly, but I cannot reproduce. Please provide clear steps to reproduce and re-open if this is still valid.
