### ISSUE TITLE
the business terms and revocation checkboxes showing under every payment method

### ISSUE THREAD

**Issue by Moppelfett** [firegento/firegento-magesetup2#77]
Hi,

As you can see on the image, the business terms and revocation checkboxes showing up under every payment method.

![unbenannt-1](https://cloud.githubusercontent.com/assets/12279931/24502719/3ef57b08-154f-11e7-87d5-9c29aede1dde.jpg)

Isn't it possible to show it up only 1 time at the buttom above the "order now button"?

Best Regards

**Comment by frostblogNet** [comment]
Hi @Moppelfett 

magesetup2 is only providing the information for terms and revocation here. The terms and revocation feature itself is a core magento feature. You could switch the view for "Display Billing Address On" to "Payment Page". You will find this setting under Configuration -> Sale -> Checkout -> Checkout option. 
![grafik](https://user-images.githubusercontent.com/19548641/85922601-f2632880-b884-11ea-9c36-96d82c4a012e.png)

This mide help.
