### ISSUE TITLE
Configurable products hidden after magesetup:setup:run

### ISSUE THREAD

**Issue by MikeBecker** [firegento/firegento-magesetup2#79]
Hi there,

i'm facing a strange behavoir with configurable products after magesetup:setup:run.
![screenshot-2017-04-19-13 36](https://cloud.githubusercontent.com/assets/804838/25178300/96bb9816-2505-11e7-9d72-6cea180612cd.jpg)

### General

* Module version: 2.0.1
* Magento version: 2.1.5
* PHP version: 7.0.18

### Issue description

I setup a demo store with a few simple and one configurable product. The product grid/list show the configurable product without it's generade simples. After i run "bin/magento magesetup:setup:run de" the configurable product isn't visible in the list any longer. Therefore all generated simples are visible which is not the behavior i want.

### Steps to reproduce

1. Add configurable product with some generated simples (attribute color)
2. Check the grid/list (only configurable product should be visible)
3. Run bin/magento magesetup:setup:run CODE
4. Recheck the grid/list (only the simple products where shown. configurable is gone)

Do I miss some configuration? Reindexing and Cache flushing has no effect. Please give me advice. Big Thanks!!!

**Comment by MikeBecker** [comment]
Ok I figured out the problem. The run command change the product settings (configurable main product and it's childs). Parent product was set to "out of stock". Child products visibility for store view was set to catalog/search instead of the default config "Not visible individually". (Screenshot) After I do the reconfiguration every thing works like expected. 

I looks that it will only a problem if you do magesetup:setup:run after you add your products. In the most cases you first do magesetup and than add your products. But I think it should work in both way. Or what do you think?

![magesetup_product_visibility](https://cloud.githubusercontent.com/assets/804838/25218842/9c890c7c-25ac-11e7-8493-cf21a1a5968d.jpg)

**Comment by MikeBecker** [comment]
After magesetup:setup:run all configurable products are changed into simple products and the configuration totally gone....

**Comment by strictlymedia** [comment]
I do have the same problem. Whole shop was broken. Is there any fix for that problem.

**Comment by dsv75** [comment]
The problem still exists today with Magento 2.2.1 (PHP7.0). Even the best catalog gets messed up and repairing the added data errors is a lot of manual work, i.e. very expensive.

Please warn openly until this problem is fixed.

**Comment by tdachev** [comment]
The problem still persists! Magento ver. 2.2.5

**Comment by frostblogNet** [comment]
Hi I tried to reproduce your issue but it is working for me on magento 2.3.5-p1 and magesetup2 0.2.0 

But if you still have issues with this please feel free to reopen. 

Thanks

**Comment by frostblogNet** [comment]
This issue is valid. If you change the tax class on a config product it will become a simple. Currently we are not sure if this is a magento or magesetup bug.

**Comment by sprankhub** [comment]
I tried to reproduce this again, but was not successful. I have the feeling that it might have been fixed with https://github.com/firegento/firegento-magesetup2/commit/7df927ea1215dbfc4d701da03426f529e49e6fda#diff-378aa0abcac53e9cd2f8433052d70a79450bf95c7e37d3f74ed75b6e4ca046bd.

If anyone can reproduce this again, please try with the latest Magento and extension version and update the steps to reproduce. Thanks!
