### ISSUE TITLE
Blank page on Magento after Installation

### ISSUE THREAD

**Issue by YugiFanGX** [firegento/firegento-magesetup2#82]
### General

* Module version: latest
* Magento version: 2.1.7
* PHP version: 7.0

### Issue description

I downloaded magesetup using composer and followed the instructions in the GitHub README.
When I try to access my Magento URL, the page is blank in Firefox, and Chromium tells me Error 500.
What can I do?

**Comment by kkrieger85** [comment]
Does this even happen if you only install M2 + magesetup2? 
Wich other extensions do you use?

**Comment by JoergLindner** [comment]
I have the same with 2.1.9 and PHP 7.0.24. Absolutly new M2 installtion and with no additional extension. As the CLI is only PHP5.6.31 at our server, the installtion will work (manually not with composer, as 2.1.9 require PHP 7).  It is still a strugle to install to a Plesk server (CLI PHP normally 5.4) M2. We 'upgraded' the CLI to 5.6.31, so at least no failure during installation of 2.1.9 (with 2.2 no failure even with original CLI PHP 5.4 installed). The Domain itself was running on PHP 7.0.24.
Under M2.2 no way to install the extension with CLI PHP 7.0.24. Under M2.1.9, a manual installation seems to be OK with the result of a white screen, while using in CLI and Domain PHP 5.6.31.

**Comment by frostblogNet** [comment]
I can not reproduce this issue. Maybe this is relatet to the magento or php version. 

I tried it with magneto 2.3.5-p1 and php 7.3.17

If you till have this isses please reopen this ticket.
