### ISSUE TITLE
Not working if running with IT as country

### ISSUE THREAD

**Issue by teoteo** [firegento/firegento-magesetup2#83]
### General

* Module version: firegento-magesetup2-develop
* Magento version: 2.1.8
* PHP version: 7.0.20

### Issue description

Giving the command bin/magento magesetup:setup:run it
I get
```
Start setup
Start processor: agreements
Start processor: cms
Start processor: email
Start processor: systemConfig
Start processor: tax
Setup finished
```

but I can’t see taxes rules or other visible changes in Magento 2.1.8 installation

### Steps to reproduce

1. Magento installed with Composer;
2. Created 2 store views (shortcode en and it);
3. Install with this procedure:
```
composer config repositories.firegento_magesetup vcs git@github.com:firegento/firegento-magesetup2.git
composer require firegento/magesetup2:dev-develop
php bin/magento module:enable FireGento_MageSetup
php bin/magento setup:upgrade
php bin/magento magesetup:setup:run it
php bin/magento setup:static-content:deploy
php bin/magento cache:flush
```

**Comment by mautz-et-tong** [comment]
The config node (<setup name="it">) in etc/magesetup.xml for IT is empty, so there is nothing to do for magesetup. Feel free to add tax rules and other stuff according to already set up nodes like de or uk.

**Comment by frostblogNet** [comment]
Version 0.2.0 provides a setup for it. Please give it a try and reopen this ticket if it is still an issue.
