### ISSUE TITLE
Magento supports 7.0.2, 7.0.4, and 7.0.6 or later.

### ISSUE THREAD

**Issue by jakerupp** [firegento/firegento-magesetup2#85]
Please make sure that you provide as much information as possibl - thank you!

### General

* Magento version: 2.2.0
* PHP version: 7.0.24

### Issue description

While running `bin/magento module:enable FireGento_MageSetup` I get the error "Magento supports 7.0.2, 7.0.4, and 7.0.6 or later. Please read http://devdocs.magento.com/guides/v1.0/install-gde/system-requirements.html" 

I don't understand the error because I am running PHP 7.0.24 which should be supported.

I am quite new to magento, so I do not know how to proceed. Maybe someone can help me.

Thanks and Regards

### Steps to reproduce

1. run `bin/magento module:enable FireGento_MageSetup`

**Comment by robineero** [comment]
I have the same question. Does anybody have soluton available for that?

**Comment by CybotTM** [comment]
How did you check your PHP version? Did you ensure you PHP CLI has also the correct version? Please run php --version on your shell where you run bin/magento
