### ISSUE TITLE
ValidationException on searchresult

### ISSUE THREAD

**Issue by lexwet** [firegento/firegento-magesetup2#86]
### General

* Module version: newest from GitHub [de]
* Magento version: 2.2
* PHP version: 7.0.24
* Mode: developer

### Issue description
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 1054

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 1054

#0 /var/www/vhosts/myhost/httpdocs/sandbox/shop/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1...

### Steps to reproduce

1. Install firegento-magesetup2
2. Search for something in the store

**Comment by lexwet** [comment]
I don't know if this right solution, but searchresult page works well when the <body> tag removing  from /httpdocs/sandbox/shop/app/code/FireGento/MageSetup/view/frontend/layout/catalogsearch_result_index.xml

**Comment by BorisovskiP** [comment]
This issue could not be reproduces in the version 0.2.0 of the module installed on Magento Version: 2.3.5-p1

**Comment by frostblogNet** [comment]
Same for me. I will close the issue here please feel free to reopen it.
