### ISSUE TITLE
Login data for "firegento-magesetup2"

### ISSUE THREAD

**Issue by Ron16** [firegento/firegento-magesetup2#9]
Hallo,
wenn ich die Installation mit Composer (ssh/putty) starten möchte, dann werde ich nach Username und Passort gefragt. 
(Eingegebener Befehl: "php composer.phar require firegento/magesetup2 dev-develop")
 
Welche Daten müssen hier denau angegeben werden?
ich habe es mit meinen SSH-Zugangsdaten versucht, aber laut Fehermeldung benötige ich ja die Zugangsdaten von "repo.magento.com/packages.json".

Es kommt folgende die Fehlermeldung:
Invalid credentials for 'https://repo.magento.com/packages.json', aborting.

Wo finde ich die richtigen Zugangsdaten?

Vielen Dank für eure Hilfe
Gr. Ron16

**Comment by therouv** [comment]
Hi @Ron16 you need to create an account on magento.com - in your account, you can create the necessary API access token which are required here.
