### ISSUE TITLE
not able to install on php 7.1.11

### ISSUE THREAD

**Issue by matin73** [firegento/firegento-magesetup2#91]
hello,

can you please update module so that it can be installed on latest php version?

  Problem 1
    - firegento/magesetup2 dev-develop requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.11) does not satisfy that requirement.
    - firegento/magesetup2 dev-develop requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.11) does not satisfy that requirement.
    - Installation request for firegento/magesetup2 dev-develop -> satisfiable by firegento/magesetup2[dev-develop].

thanks!
martin

**Comment by roman204** [comment]
see https://github.com/firegento/firegento-magesetup2/blob/develop/composer.json, its updated to ~7.1.0 wich allows also 7.1.X
