### ISSUE TITLE
Layout Errors when upgrading to Magento 2.2

### ISSUE THREAD

**Issue by danielmaier42** [firegento/firegento-magesetup2#92]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 2.0.1
* Magento version: 2.2.1
* PHP version: 7.0.20

### Issue description

When upgrading to Magento 2.2 the layout.xml checking is improved and throws errors when xml-files are not correctly formatted. The problem persists in File `catalogsearch_result_index.xml` because `update` Node is inside of `body` Node.

### Steps to reproduce

1. Install Magento 2.2 or Update from earlier Version
2. Install FireGento MageSetup2
3. Perform Search

**Comment by Kipperlenny** [comment]
sorry did not see your issue: https://github.com/firegento/firegento-magesetup2/pull/94
