### ISSUE TITLE
once installed checkout can't be completed

### ISSUE THREAD

**Issue by pixxet** [firegento/firegento-magesetup2#97]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: latest
* Magento version: 2.2
* PHP version: 7.0

### Issue description

once installed checkout can't be completed

**Comment by dsv75** [comment]
I second this. Checkout only works on a current MS Edge or Chrome, but not on a current Mozilla or Epic.

Magento: 2.2.1
PHP version: 7.0.25
Module version: latest

**Comment by roman204** [comment]
Can you provide more information please?
In which step is it not working? 
Is a error shown? 
How to reproduce the behavior?

**Comment by pixxet** [comment]
in the last part of placing an order

clicking the place order button has no affect in safari or mozilla

i can prepare a sandbox with access to ftp and DB where you can reproduce the bug and control the logs

**Comment by roman204** [comment]
This is not a affect of firegento module, its a magento error see https://github.com/magento/magento2/issues/11885

**Comment by BorisovskiP** [comment]
Tested on Magento Version : **2.3.5-p1**, module version**0.2.0**, Firefox Version **77.0.1**, the issue could not be reproduced.
