### ISSUE TITLE
Search Error / Firegento-Magesetup2 Installed

### ISSUE THREAD

**Issue by unifiedarts** [firegento/firegento-magesetup2#98]
Hey guys we found an error within your module. As soon you're searching for products you get this one:

`Magento\Framework\Config\Dom\ValidationException: Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ). Line: 655 in /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Config/Dom.php:402 Stack trace: #0 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Config/Dom.php(116): Magento\Framework\Config\Dom->_initDom('__construct('createObject('Magento\\Framewo...', Array) #3 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array) #4 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array) #5 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array) #6 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('_validateMergedLayout('LAYOUT_frontend...', '\n load() #9 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Model\Layout\Merge\Interceptor->___callParent('load', Array) #10 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Model\Layout\Merge\Interceptor->Magento\Framework\Interception\{closure}() #11 /var/www/share/example.com/htdocs/storename/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(195): Magento\Framework\View\Model\Layout\Merge\Interceptor->___callPlugins('load', Array, Array) #12 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load() #13 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates() #14 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build() #15 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build() #16 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild() #17 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates() #18 /var/www/share/example.com/htdocs/storename/vendor/magento/module-catalog-search/Controller/Result/Index.php(91): Magento\Framework\App\View->loadLayout() #19 /var/www/share/example.com/htdocs/storename/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(24): Magento\CatalogSearch\Controller\Result\Index->execute() #20 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/Action/Action.php(107): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute() #21 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #22 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array) #23 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #24 /var/www/share/example.com/htdocs/storename/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array) #25 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #26 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #27 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #28 /var/www/share/example.com/htdocs/storename/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #29 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #30 /var/www/share/example.com/htdocs/storename/app/code/Mirasvit/SearchAutocomplete/Plugin/ResponsePlugin.php(166): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #31 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\SearchAutocomplete\Plugin\ResponsePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #32 /var/www/share/example.com/htdocs/storename/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #33 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #34 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #35 /var/www/share/example.com/htdocs/storename/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #36 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #37 /var/www/share/example.com/htdocs/storename/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch() #38 /var/www/share/example.com/htdocs/storename/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #39 {main}`

### General

* Module version: 2.0.1
* Magento version: 2.2.1
* PHP version: 7.0.1

### Issue description
see above
...

### Steps to reproduce

1. enter search string
2. press enter

### Solution:
vendor/firegento/magesetup2/view/frontend/layout/catalogsearch_result_index.xml
Update should be outside body tag.

**Comment by mautz-et-tong** [comment]
Do you use the latest version? Should be fixed. See https://github.com/firegento/firegento-magesetup2/pull/94

**Comment by dakira** [comment]
This does not happen in the latest version.
