### ISSUE TITLE
Update error in magento 2.2.1

### ISSUE THREAD

**Issue by hubertus2017** [firegento/firegento-magesetup2#99]
Please make sure that you provide as much information as possibl - thank you!

### General

* Module version: 1.23.2
* Magento version: 2.2.1
* PHP version: 7.0.0

###  Error in Update! 
[2017-12-11 13:23:45 CET] An error occurred while executing job "update {"components":[{"name":"splendidinternet/mage2-locale-de-de","version":"1.35.1"}]}": Could not complete update {"components":[{"name":"splendidinternet/mage2-locale-de-de","version":"1.35.1"}]} successfully: Command "update" failed: Loading composer repositories with package information
...
....
- Updating sebastian/finder-facade (1.2.1 => 1.2.2): Downloading (connecting...)Downloading (0%) Downloading (15%)Downloading (30%)Downloading (100%)
- Updating firegento/magesetup2 dev-develop (cd78bba => f58dc3a):

[RuntimeException]
Source directory {magento_root}/vendor/firegento/magesetup2 has uncommitted changes.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] []...

**Comment by roman204** [comment]
That error is thrown cause you have changed some files in directory vendor/firegento/magesetup2. Please revert those changes and the update should work.

**Comment by hubertus2017** [comment]
hello,
thanks for the quick reply. i did not change anything in the folder.

How can i make a clen new installation?

**Comment by roman204** [comment]
- Deleted that particular library's folder
- composer update --prefer-source vendor/library-name
It fetches the library again along with it's git repo

**Comment by hubertus2017** [comment]
Ok, i made like this. 
Now no "available update" is visible in the extension manager (as i have the neweset version now?).

Hopefully it works the next time.

I noticed the old library folder had permission rwxrws---  2770 and the new downloaded has rwxrwsr-x 2775
